### ISSUE TITLE
Error while linking on Tioga (AMD) with GasNET

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1555] opened 2023-09-28 18:04 UTC
I am working on porting HTR on Tioga (https://hpc.llnl.gov/hardware/compute-platforms/tioga) and, as soon as I try to link my any application with Legion, I get errors.
I am using CMake to build Legion and I've tryied two options without success

**Option 1: Using the embedded GasNet:**

I configure legion with the following command line
```
cmake -DLegion_USE_GASNet=ON -DLegion_USE_HIP=ON -DLegion_USE_HDF=ON -DLegion_USE_OpenMP=ON -DLegion_EMBED_GASNet=ON -DGASNet_CONDUIT=ofi -DGASNet_SYSTEM=slingshot11 .
```
I build it with 
```
make -j
```
Then I try to test the installation building circuit. I configure circuit in the folder `examples/circuit/` with the following command
```
Legion_DIR=$LEGION_DIR cmake -DCMAKE_HIP_ARCHITECTURES=gfx90a .
```
and when I try to make it with `make -j`, I get the error 
```
make[2]: *** No rule to make target '/usr/local/lib64/libgasnet-ofi-par.a', needed by 'circuit'.  Stop.
```
Meaning that it is pointing to the wrong path to find gasnet.

**Option 2: Forcing the path to GasNet:**

Considering that with the previous attempt the cmake system has already built a gasnet in the folder `/g/g92/direnzo1/legion_tioga/embed-gasnet/install/`, I try to force to path to gasnet by building Legion with 
```
cmake -DLegion_USE_GASNet=ON -DLegion_USE_HIP=ON -DLegion_USE_HDF=ON -DLegion_USE_OpenMP=ON -DGASNet_ROOT_DIR=/g/g92/direnzo1/legion_tioga/embed-gasnet/install -DGASNet_CONDUIT=ofi -DGASNet_SYSTEM=slingshot11 .
```
 
In this case, if I try to build circuit with the same commands above, I get the following errors:
```
ld.lld: error: undefined symbol: MPI_Initialized
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a
>>> did you mean: PMI_Initialized
>>> defined in: /opt/cray/pe/pmi/default/lib/libpmi2.so

ld.lld: error: undefined symbol: MPI_Query_thread
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Init_thread
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Comm_group
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Comm_create
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Group_free
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Comm_size
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Comm_rank
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(gasneti_bootstrapInit_mpi) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Finalized
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapFini) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Comm_free
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapFini) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Finalize
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapFini) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Abort
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapAbort) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Barrier
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapBarrier) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Allgather
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapExchange) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Alltoall
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapAlltoall) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Bcast
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapBroadcast) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Isend
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapSNodeBroadcast) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Waitall
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapSNodeBroadcast) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a

ld.lld: error: undefined symbol: MPI_Recv
>>> referenced by gasnet_bootstrap_mpi.c
>>>               gasnet_bootstrap_mpi-PAR.o:(bootstrapSNodeBroadcast) in archive /g/g92/direnzo1/legion_tioga/embed-gasnet/install/lib/libgasnet-ofi-par.a
```

I am not expert in the cmake system to build legion but it seems that the dependecies of GasNet are not correctly propagated.
I was wondering if you have any advise? 

NOTE: if I deactivate the support of GasNET, the codes link fine.

**Comment by mariodirenzo** [comment] 2023-09-30 12:20
@elliottslaughter, please add this issue to https://github.com/StanfordLegion/legion/issues/1032

**Comment by elliottslaughter** [comment] 2023-10-03 23:03
Could you share your values of `CC` and `CXX`? Or maybe if possible, upload the `CMakeCaches.txt`.

**Comment by mariodirenzo** [comment] 2023-10-04 07:08
The CMakeCaches.txt of an installation generated with option 1 is
[CMakeCache_badOpt1.txt](https://github.com/StanfordLegion/legion/files/12800400/CMakeCache_badOpt1.txt)

The CMakeCaches.txt of an installation generated with option 2 without the patch above is
[CMakeCache_badOpt2.txt](https://github.com/StanfordLegion/legion/files/12800387/CMakeCache_badOpt2.txt)

The CMakeCaches.txt of a fully functional installation generated with option 2 and the patch above is
[CMakeCache_goodOpt2.txt](https://github.com/StanfordLegion/legion/files/12800363/CMakeCache_goodOpt2.txt)

The failure with option 1 is somehow related to this line of code, though I haven't been able to get a good installation
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/CMakeLists.txt#L472

**Comment by elliottslaughter** [comment] 2024-07-03 22:50
I posted your suggested patch with minor modifications here:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/1362

**Comment by elliottslaughter** [comment] 2024-07-09 23:47
I merged the patch into `master`, @mariodirenzo please confirm that the issue is fixed.

**Closed** 2024-07-10 10:24 UTC
