### ISSUE TITLE
Confusion between cmake and make builds

### ISSUE THREAD

**Issue by ahenzinger** [StanfordLegion/legion#793] opened 2020-03-28 18:14 UTC
If one switches between the cmake and make builds, regent.py can be confused about where the new binary is (because they are built in different locations). It may be useful for regent.py to look at the most recent binary, or for both builds to produce a binary in the same location.

**Comment by lightsighter** [comment] 2020-03-28 20:52
The make build system has an `install` option now which can be used to put legion libraries and binaries in the same places that cmake might have normally put them.

**Comment by elliottslaughter** [comment] 2020-03-30 17:28
@ahenzinger Can you help me by attaching instructions to reproduce this? Or if you don't have precise instructions, at least a general sense of what you were doing would help. At the moment it's difficult to know what to look for.

I don't think binary location should be an issue because Regent stores the value of the most recent CMake/Make build in `.cmake.json`, so there really shouldn't be any way for it to get confused about that. The main thing I can think of is that Make does an in-source build which leaves a bunch of artifacts if you don't clean up before switching to CMake. Going the other direction shouldn't be an issue because CMake always builds out-of-source.

**Comment by ahenzinger** [comment] 2020-03-31 21:59
I think what I did was alternate between calling ./install.py with --no-cmake and without that flag. What I observed was that, when I built everything and ran stencil, it seemed fine but was giving me some weird behavior in some cases. This problem was fixed when I deleted the 'build/' folder in 'legion/language/', because then it was using the correct binary. I think this is exactly what you're referring to (in terms of the Make build leaving artifacts that need to be cleaned up, otherwise regent.py can get confused).

**Comment by elliottslaughter** [comment] 2020-04-09 21:44
I've been trying to do everything I can to get this to mess up, and I just don't see any problems. All of these work as expected.

```
./install.py --rdir=auto --cmake --debug
./regent.py examples/circuit_sparse.rg
./install.py --rdir=auto --no-cmake --debug
./regent.py examples/circuit_sparse.rg
./install.py --rdir=auto --cmake --debug
./regent.py examples/circuit_sparse.rg
rm -rf build/
./install.py --rdir=auto --cmake --debug
./regent.py examples/circuit_sparse.rg
```

Unfortunately, I don't think I can debug this without concrete and reproducible steps for reproduction.

**Comment by ahenzinger** [comment] 2020-04-09 21:56
That's not a problem, sorry for not having reproducible steps, I just thought I'd mention this issue.

In case it helps, think something I called that also may have contributed to messing things up is 'scripts/setup_env.py' (I called this after previously using 'CONDUIT=ibv ./install.py --cuda --llvm --hdf5 --no-cmake --gasnet').

**Comment by streichler** [comment] 2020-12-27 23:04
Closing this out as "not reproducible".  An actual reproduction of the issue is grounds for reopening it.  :)

**Closed by streichler** 2020-12-27 23:04 UTC
Labels: Build, Regent, best effort, planned
