### ISSUE TITLE
Legion: Merge piece lists for fields of same size

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#559] opened 2019-06-27 05:53 UTC
When running S3D ctrlrepl branch with the PRF mechanism, I hit the following assertion:

``s3d.x: .../legion/runtime/realm/inst_impl.cc:734: void Realm::RegionInstanceImpl::Metadata::serialize_msg(T&) const [with T = ActiveMessage<Realm::MetadataResponseMessage>]: Assertion `ok' failed.``

A bit of debugging seems to show this is occuring when we are trying to serialize 93584 bytes into a 65536 byte fixed-size buffer. The vast majority of the bytes are going into the layout, which appears to be:

`Layout(bytes=109314048, align=32, fields={1001=0+0, 1002=1+0, 1003=2+0, 1006=3+0, 1017=468+0, 1019=469+0, 1021=470+0, 1023=471+0, 1025=472+0, 1027=473+0, 1029=474+0, 1031=475+0, 1033=476+0, 1038=477+0, 1040=478+0, 1042=479+0, 1044=480+0, 1046=596+0, 1048=712+0, 1050=481+0, 1052=597+0, 1054=713+0, 1056=482+0, 1058=598+0, 1060=714+0, 1062=483+0, 1064=599+0, 1066=715+0, 1068=484+0, 1070=600+0, 1072=716+0, 1074=485+0, 1076=601+0, 1078=717+0, 1080=486+0, 1082=602+0, 1084=718+0, 1086=487+0, 1088=603+0, 1090=719+0, 1092=488+0, 1094=604+0, 1096=720+0, 1098=489+0, 1100=605+0, 1102=721+0, 1104=490+0, 1106=606+0` (... and it goes on for quite some time ...)

An immediate workaround is to replace two cases of `65536` in `inst_impl.cc` and `metadata.cc` with a larger value (e.g. `1<<18`). But this layout could be described much more compactly if the piece lists were merged (or so @streichler tells me).

**Comment by lightsighter** [comment] 2019-06-27 06:13
All Legion piece lists are generated by Realm code currently:
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/region_tree.inl#L2861-2862
@streichler What needs to happen to make that Realm code more efficient?

**Comment by lightsighter** [comment] 2019-06-27 08:29
Actually looks like the problem is this TODO in Realm here:
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/realm/inst_layout.inl#L108

**Comment by streichler** [comment] 2019-07-07 21:33
Commit 169f514 tries to optimize this case.  @elliottslaughter can you try this out with S3D and see if it works without the message size workaround?

**Comment by lightsighter** [comment] 2019-07-08 01:03
I was having the same problem with S3D and it seems to be fixed now, at least for me.

**Comment by lightsighter** [comment] 2019-07-16 06:10
Unless @elliottslaughter wants to complain I'm going to close this issue tomorrow since I verified the fix.

**Closed** 2019-07-16 15:52 UTC
Labels: Legion, Realm
