### ISSUE TITLE
collector issue for improved error messages

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#851] opened 2020-05-21 22:58 UTC
#1
Mike, can you help me understand how this statement
    348   typedef const FieldAccessor<READ_WRITE, ImageReduction::PixelField,
    349     image_region_dimensions,
    350     coord_t, Realm::AffineAccessor<ImageReduction::PixelField,
    351     image_region_dimensions, coord_t> > RWAccessor;
    352 __TRACE
    353   RWAccessor r0In(image0_pr, ImageReduction::FID_FIELD_R);
can generate this error message? the error is from line 353
[0 - 7fb23f928700] {5}{runtime}: [error 164] LEGION ERROR: Dynamic type mismatch in 'get_index_space_domain' (from file /home/aheirich/Documents/Legion/software/legion/runtime/legion/region_tree.inl:1950)[error 164]

aheirich  11:08 AM
I found it - the physical region had been created with a 2D index space but the accessor was 3D.
In retrospect I can understand this message, but when I first read it the word "type" made me think the problem was the data type.  This is confusing.

lightsighter:rocket:  3:52 PM
legion can't tell the difference in realm's type encodings, all it has is an in integer and we don't know whether that integer is different because the coordinate type is different or the dimensions are different

aheirich  3:53 PM
then could the error message say that? that would be more helpful
New

lightsighter:rocket:  3:55 PM
i think you should just start making notes on this on the github issue for improved error messages, i'm not going to be going through and changing lots of error messages that will create a bunch of unnecessary conflicts in other branches that are outstanding right now

**Comment by lightsighter** [comment] 2020-05-22 00:12
This is a duplicate of #632. Please move all your comments there and close this issue.

**Comment by lightsighter** [comment] 2020-05-24 22:01
I moved this over.

**Closed by lightsighter** 2020-05-24 22:01 UTC
