### ISSUE TITLE
Legion: missing debug symbols in outputs

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#761] opened 2020-02-26 19:04 UTC
When using the CMake Debug build (static or shared), then linking with a Legion application, debug symbols are not output to the terminal when running with flags like `-lg:warn_backtrace` or exporting `LEGION_BACKTRACE=1`.

**Comment by elliottslaughter** [comment] 2020-02-26 19:06
@streichler I can reproduce this; `gdb` works fine (I get backtraces with line numbers, variables, the whole shebang) but somehow Realm's own backtraces don't work. Any ideas?

**Comment by elliottslaughter** [comment] 2020-02-26 19:54
The solution to this is to set the property `ENABLE_EXPORTS` on the user's application. See [the CMake documentation](https://cmake.org/cmake/help/v3.6/prop_tgt/ENABLE_EXPORTS.html) for details. This results in adding `-rdynamic` to the link command line.

Example of doing this in a CMake file:

```
    set_target_properties(my_executable
        PROPERTIES
            ENABLE_EXPORTS ON)
```

It's not obvious to me if we should attempt to fix this at the Legion level or not, since if we do so it will force what is currently an application-specific setting.

**Comment by lightsighter** [comment] 2020-02-27 09:25
CMake being stupid strikes again!

**Comment by elliottslaughter** [comment] 2020-02-27 18:21
I don't know that I'd characterize it like that, in Make this only works because we force it for all applications by setting `-rdynamic`. But if you were starting with Make from scratch you'd have to discover this flag yourself, just like we had to discover it with CMake.

I think the big open question is whether we want to try to set CMake up so that the setting is "infectious" (basically taking the decision away from our users as to whether to set this or not; currently this is something users get to choose on their own). The most obvious way to do that is to set `CMAKE_ENABLE_EXPORTS`, but there may be a more idiomatic way to do it.

**Comment by streichler** [comment] 2020-02-27 20:12
It occurs to me that `-rdynamic` is also necessary for Realm's portable task registration of function pointers, so I'd advocate for it being infectious, at least by default.

**Comment by lightsighter** [comment] 2020-03-02 00:18
> currently this is something users get to choose on their own

Why should users ever be responsible for setting `-rdynamic`? It's a property of the code being built and the functionality that it needs, which is not something the user should ever need to know. Again CMake made a bad design decision and we're left cleaning up the pieces.

**Comment by streichler** [comment] 2020-03-29 00:25
So for what it's worth, this appears to be broken with the makefile-based install setup as well.

Building the dynamic_registration example against the installed headers and libs appears to compile fine, but fails at runtime because `dladdr` calls fail.  The problem is fixed by adding `-rdynamic` to the link line, but the problem of "how does an application's build know to add flags to its link line beyond just the name of the library it wants" is more general than a single build tool.

**Comment by streichler** [comment] 2021-04-02 04:11
So there doesn't seem to be a way to set a property on a library that causes cmake to set the ENABLE_EXPORTS property on an executable, so I've gone with the brute force approach of adding 
```
set(CMAKE_ENABLE_EXPORTS ON)
```
to the exported cmake config, which fixes at least the test case I was looking at.  This is in a branch, but will probably fold into
the master branch early next week.

**Comment by elliottslaughter** [comment] 2021-06-15 22:19
@streichler Did we end up folding that branch in?

**Comment by streichler** [comment] 2021-06-15 22:57
Yes, commit 5c986204 is in the master branch and therefore should show up in the 21.06 release.

**Closed** 2022-03-02 05:02 UTC
Labels: bug, Build, planned, best effort
