### ISSUE TITLE
mpi_interop.cc test hangs when executed with 2+ mpi processes 

### ISSUE THREAD

**Issue by ipdemes** [StanfordLegion/legion#211] opened 2016-11-28 20:48 UTC
I have built the test with GASNET 1.26.4, mpi conduit and getting the test hanging when running it with 2+ mpi processes.

**Comment by lightsighter** [comment] 2016-11-29 07:29
Do you see warnings that look like this:
opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once

I think the problem is that you can't be performing multiple MPI calls from different threads in the same process at the same time which is happening here because the application is calling MPI_Barrier on the MPI side and GASNet is polling with an MPI_IRecv internally to emulate active messages.

Can you try a different conduit: IBV, Gemini, or Aires?

**Comment by ipdemes** [comment] 2016-11-29 18:42
Hi Mike,

Thank you for the reply. I haven't got that warning, but I have just tried using ibv conduit of GASNET and got the test running with no issues.  Is it possible to check what conduit is used in the example and set strict_bulk_synchronous_execution=false in case of MPI one?

**Comment by lightsighter** [comment] 2016-11-29 19:27
I tried that last night too.  I ran into issues with calling MPI_Finalize on the MPI-side racing with the GASNet shutdown which I think was still trying to do MPI calls when using the MPI conduit.  

Just talking with Sean on slack and I think we both agree that GASNet's MPI conduit does not support MPI-interop.  Not too surprising I think considering MPI calls from two different sides of the applications will run into all sorts of trouble.  We're at least going to add a comment to the example that it only works with conduits that support MPI-interop, and if possible add a compile-time check for MPI-interoperability on the conduit.

**Comment by ipdemes** [comment] 2016-11-29 19:37
I see. Could you, please, point me to your discussion with Sean (I didn't see it on Slack/general)?
It would be helpful if you could provide the list of the conduits working with MPI-interoperability. I can use ibv on our cluster, but I am not sure which one to use on my local machine.

**Comment by lightsighter** [comment] 2016-11-29 22:31
We had the discussion in our private channel.  As far as we can see, the only conduits that support MPI-interoperability are: IBV, Gemini, Aries, MXM, and OFI.  Note this isn't a function of Legion, but of what is implemented in GASNet, so you would have this problem even if you weren't using the Legion-MPI interop.  Expect to see an email from me to the GASNet developers asking them for UDP support later today.

I've added a comment to the example about which conduits currently work to the example and I'm going to close the issue.

**Closed by lightsighter** 2016-11-29 22:31 UTC

**Comment by ipdemes** [comment] 2016-11-29 23:48
Hi Mike, 
Thank you for sending message to Gasnet developers about the issue.
One update from my side:
We solve the issue with MPI_Finalize and MPI conduit in FLeCSi just by not calling MPI_Finalize function when our code built with Gasnet+mpi. Plus, I guess we can still use MPI conduit for MPI-legion codes as far as we make sure we don't  have MPI calls from 2 different runtimes at the same time (having them be bulk synchronous). For example, just removing MPI_Barriers from mpi_interop example I have got it running with mpirun -n2. But I assume this can't be a long-term strategy for MPI interoperability in legion.

**Comment by lightsighter** [comment] 2016-11-30 06:52
Yes, I think you've just found a temporary fix cause you're not calling MPI from the actual MPI thread, which you're obviously going to need to do in the future. :)  I'm about to send a new email to the Paul to update you guys on what I've discovered.

**Comment by lightsighter** [comment] 2016-11-30 18:05
@ipdemes Can you try the modified MPI interop example with the MPI conduit on your laptop and tell me if it works?  You may need to rebuild your MPI implementation to support MPI_THREAD_MULTIPLE.  The example will tell you if your current MPI implementation doesn't support it.

**Comment by ipdemes** [comment] 2016-11-30 18:50
I've just istalled mpich on my machine and tried to build/run updated mpi_interop example - there was no issues with running it with mpirun -n 1,2,4. So it seems to work.

**Comment by lightsighter** [comment] 2016-11-30 19:16
Ok cool, let me know if you have any further issues.

**Comment by ipdemes** [comment] 2016-11-30 20:30
Thank you!
