### ISSUE TITLE
realm: switch default network layer to gasnetex

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#1099] opened 2021-06-14 19:17 UTC
Necessary conditions:
1. Fixing all known bugs in gasnetex implementation.
2. Enough testing at larger scales to be confident there are no blatant performance regressions.

Goal: get this done for the 21.09 release

**Comment by elliottslaughter** [comment] 2024-03-14 18:31
Duplicate of #1508

**Closed by elliottslaughter** 2024-03-14 18:31 UTC
Labels: enhancement, Realm, planned
