### ISSUE TITLE
Regent: passing arrays to tasks

### ISSUE THREAD

**Issue by rupanshusoi** [StanfordLegion/legion#724] opened 2020-01-20 10:45 UTC
The following
```c
import "regent"
task t(a : int[50000])
end
task main()
        regentlib.c.printf("hello\n")
end
regentlib.start(main)
```
takes about 2.5 minutes to run. I noticed the following:

1. The problem vanishes if I change ```t``` to a terra function.
2. If I pass a pointer to an array
```
task t(a : &int[50000])
```
the code executes almost instantly but produces a warning
```
WARNING: parameter $a has raw pointer type &int32[50000]. please consider replacing it with a non-pointer type.
```
3. Reducing the size of the array makes the code faster, but still orders of magnitude slower than it should be.
4. Surprisingly, declaring the same array inside main
```c
import "regent"
task main()
        var arr : int[50000]
        regentlib.c.printf("hello\n")
end
regentlib.start(main)

```
causes no problems, and executes immediately. 
Is passing arrays to tasks not a "Regent" way of doing things? I'm not sure if this is intentional or a bug, and any alternatives or guidance will be really appreciated.

**Comment by lightsighter** [comment] 2020-01-20 21:54
Arrays of that size should really be put into regions. Is there a reason that you're trying to pass it by value?

**Comment by rupanshusoi** [comment] 2020-01-21 10:50
I see. I'm fine with passing it by reference too. Can you tell me a way to disable that warning then?

**Comment by elliottslaughter** [comment] 2020-01-21 18:48
Just to be clear, I'm pretty sure @lightsighter was suggesting that you pass it via a region. I.e.:

```
import "regent"
task t(a : region(ispace(int1d)))
where reads(a) do
end

task main()
  var arr = region(ispace(int1d, 50000), int)
  t(a)
end
```

Or something similar.

You can't just pass a raw pointer (`&int`) because if you're running on a distributed machine, that pointer won't be valid on any other nodes (and in general, Legion can move tasks to other nodes to distribute load).

Having said all this, I do think there is a bug here, but it's a Terra bug. The extra time in your first case is probably compile time, and it's almost certainly being spent in LLVM in a pass like SROA. We saw something similar with structs earlier, that can cause them to really increase the compile times. Probably you're avoiding this when you use Terra directly because it can inline the function (which doesn't happen automatically in the Regent case).

**Comment by rupanshusoi** [comment] 2020-01-21 18:57
Thank you, this really helps.

**Comment by elliottslaughter** [comment] 2020-01-21 19:07
Just as a general rule, we recommend that any data larger than about 1 KB be put into regions, because regions do not require serialization. (Whereas any values passed by value would need to be serialized.)

I'll try to see if I can derive a small reproducer for the compile time issue (since again I'm pretty sure it's in Terra).

**Comment by elliottslaughter** [comment] 2020-01-21 20:06
Attaching some reproducers here for this issue:

  * [test_bug_724.rg.txt](https://github.com/StanfordLegion/legion/files/4093457/test_bug_724.rg.txt)
  * [test_bug_724_codegen.t.txt](https://github.com/StanfordLegion/legion/files/4093459/test_bug_724_codegen.t.txt)

The compile time seems to be going into `unpack_param`. The result of running the second reproducer looks like:

```
about to compile unpack_param
finished compile unpack_param in 163.734407 seconds
about to compile t
finished compile t in 0.008869 seconds
```

Next step is to minimize `unpack_param` to see what it's sensitive to.

**Comment by elliottslaughter** [comment] 2020-01-21 22:15
Got it minimized some more, pretty sure this is a Terra or LLVM bug. I posted the further minimized version on the Terra issue tracker: https://github.com/terralang/terra/issues/427

**Comment by elliottslaughter** [comment] 2020-01-29 01:02
This is fixed in a branch in Terra. Will merge once the PR passes.

**Comment by elliottslaughter** [comment] 2020-01-29 18:49
Merged in to Terra `master`.

**Closed by elliottslaughter** 2020-01-29 18:49 UTC
Labels: Regent, bug, planned
