### ISSUE TITLE
Reductions to remote GPU FB memories are broken

### ISSUE THREAD

**Issue by ahenzinger** [StanfordLegion/legion#579] opened 2019-08-29 20:37 UTC
The backtrace is:

Signal 11 received by node 1, process 9496 (thread 7f23af1fd700) - obtaining backtrace
Signal 11 received by process 9496 (thread 7f23af1fd700) at: stack trace: 9 frames
 [0] = /lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7f23ee6e8cb0]
 [1] = /home/ahenz/new/legion/bindings/regent/libregent.so(void PlusOpFloat::apply<false>(float&, float)+0) [0x7f23ef03db90]
 [2] = /home/ahenz/new/legion/bindings/regent/libregent.so(Realm::ReductionOp<PlusOpFloat>::apply_strided(void*, void const*, long, long, unsigned long, bool) const+0x47) [0x7f23ef045b37]
 [3] = /home/ahenz/new/legion/bindings/regent/libregent.so(Realm::RemoteReduceMessage::handle_message(int, Realm::RemoteReduceMessage const&, void const*, unsigned long)+0x1a3) [0x7f23efa714b3]
 [4] = /home/ahenz/new/legion/bindings/regent/libregent.so(IncomingMessageNew::run_handler()+0x17) [0x7f23efacf207]
 [5] = /home/ahenz/new/legion/bindings/regent/libregent.so(IncomingMessageManager::handler_thread_loop()+0x5d) [0x7f23efacdb9d]
 [6] = /home/ahenz/new/legion/bindings/regent/libregent.so(Realm::KernelThread::pthread_entry(void*)+0xf8) [0x7f23ef54f6e8]
 [7] = /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f23eda65184]
 [8] = /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f23ee7ac37d]

**Comment by lightsighter** [comment] 2019-09-06 00:23
@ahenzinger I think this is a duplicate of #372. Do you agree @streichler? See the first comment on that issue.

**Comment by streichler** [comment] 2019-09-08 19:49
This should be functionally correct now with commit c0016e6.  @ahenzinger can you double-check that this works without any additional patches applied?  And yes, it basically is a duplicate of #372, but I'm going to leave that one open because both local and remote gpu reductions are still much slower than we'd like (because they bounce off of sysmem).

**Comment by ahenzinger** [comment] 2019-09-12 05:24
Yes, this fixes the issue I was having without any additional patches applied!

**Comment by lightsighter** [comment] 2019-09-12 06:17
Ok, I'm going to close this issue. Any further issues we have with reductions to GPU memories can be reported on issue #372.

**Closed by lightsighter** 2019-09-12 06:17 UTC
