### ISSUE TITLE
assert in soleil-x master branch at runtime/realm/metadata.cc:95:  on piz daint

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#328] opened 2017-10-27 23:43 UTC
this assert does not happen on sapling

srun -n 4 -N 4 --ntasks-per-node 1 --cpu_bind none /lib64/ld-linux-x86-64.so.2 /users/aheirich/PSAAP/soleil-master/src/piz_daint_jobs/Job_4_master/taylor-512x512x256-shardsize1 -ll:cpu 2 -ll:util 2 -ll:dma 2 -ll:io 1 -ll:csize 40000 -ll:rsize 8192 -hl:sched -1 -level legion_prof=2,5 -logfile soleil_prof_% -hl:prof 4 -hl:serializer ascii | tee Job_4_master
taylor-512x512x256-shardsize1: /users/aheirich/PSAAP/legion/runtime/realm/transfer/channel.cc:629: long int Realm::XferDes::default_get_requests(Realm::Request**, long int, unsigned int): Assertion `src_bytes == dst_bytes' failed.
taylor-512x512x256-shardsize1: /users/aheirich/PSAAP/legion/runtime/realm/transfer/channel.cc:629: long int Realm::XferDes::default_get_requests(Realm::Request**, long int, unsigned int): Assertion `src_bytes == dst_bytes' failed.

legion repo is at 
commit a2b971e6c34cce166b3ba4181ebfadc1a71dd1c8
Author: Sean Treichler <sjt@cs.stanford.edu>
Date:   Fri Oct 27 04:21:11 2017 -0700

    release candidate for legion-17.10.0

soleil-x repo is at
commit ab8068b7c3b5637776c688145ae7a98ac47c10e5
Author: Alan Heirich <aheirich@stanford.edu>
Date:   Fri Oct 27 20:07:55 2017 +0200

    running on piz daint

The environment is fairly complex to set up, let me know if you want me to either (a) set up an environment for you to use or (b) run experiments for you in my environment

**Comment by aheirich** [comment] 2017-10-28 00:15
the previous run used -ll:cpu 2 which looks like a bug.   rerunning with -ll:cpu 4 gives a different result

srun -n 4 -N 4 --ntasks-per-node 1 --cpu_bind none /lib64/ld-linux-x86-64.so.2 /users/aheirich/PSAAP/soleil-master/src/piz_daint_jobs/Job_4_master/taylor-512x512x256-shardsize1 -ll:cpu 4 -ll:util 2 -ll:dma 2 -ll:io 1 -ll:csize 40000 -ll:rsize 8192 -hl:sched -1 -level legion_prof=2,5 -logfile soleil_prof_% -hl:prof 4 -hl:serializer ascii | tee Job_4_master
taylor-512x512x256-shardsize1: /users/aheirich/PSAAP/legion/runtime/realm/metadata.cc:95: Realm::Event Realm::MetadataBase::request_data(int, Realm::ID::IDType): Assertion `owner != my_node_id' failed.
Legion process received signal 6: Aborted

**Comment by aheirich** [comment] 2017-10-28 00:17
note that it would be useful to identify the source of the error in the case where we are running with -ll:cpu 2 but should have -ll:cpu 4.  I don't know whether this is possible.

**Comment by streichler** [comment] 2017-10-28 02:51
@aheirich please run both cases (i.e. `-ll:cpu 2` and `-ll:cpu 4`) with `-level inst=1,dma=2` and put the log files on sapling where I can look at them.  While the `-ll:cpu 2` case may be unintended, the error you're getting shouldn't happen even with a "bad" partitioning or placement.

**Comment by aheirich** [comment] 2017-10-28 06:51
@streichler logs are at http://sapling.stanford.edu/~aheirich/soleil_prof_cpu2_0 and http://sapling.stanford.edu/~aheirich/soleil_prof_cpu4_0

**Comment by streichler** [comment] 2018-01-02 19:52
@aheirich I made some changes in November that might have fixed this.  Can you give it another try and let me know what you find?  Thanks.

**Comment by streichler** [comment] 2019-10-08 12:50
@aheirich unless you've got a new reproducer for this, I'm going to close it out.

**Closed** 2020-02-05 19:53 UTC
Labels: bug
