### ISSUE TITLE
Unable to run ./install.py

### ISSUE THREAD

**Issue by sierrakn** [StanfordLegion/legion#212] opened 2016-12-08 22:41 UTC
Getting this error:

clang: error: no such file or directory: '/usr/bin/../include'
make: --includedir: Command not found
/bin/sh: --: invalid option
Usage:	/bin/sh [GNU long option] [option] ...
	/bin/sh [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
make: *** [build/main.o] Error 1
Traceback (most recent call last):
  File "./install.py", line 298, in <module>
    driver()
  File "./install.py", line 295, in driver
    install(**vars(args))
  File "./install.py", line 240, in install
    install_terra(terra_dir, external_terra_dir, thread_count)
  File "./install.py", line 148, in install_terra
    build_terra(terra_dir, thread_count)
  File "./install.py", line 113, in build_terra
    cwd = terra_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'all', '-j', '8']' returned non-zero exit status 2

**Comment by streichler** [comment] 2016-12-08 22:45
It looks like the build of Terra is having trouble.  Can you provide some detail about your system?
Do you have clang installed?  If so, what version?

**Comment by sierrakn** [comment] 2016-12-08 22:58
Yeah it is Terra. I have LLVM version 8 (clang-800.0.42.1) and  I'm on a
Mac.

**Comment by elliottslaughter** [comment] 2016-12-08 23:03
If you're using LLVM from XCode, I don't think it includes the headers you'll need to build Terra. I believe LLVM/Clang binaries from llvm.org should generally work (for LLVM versions >= 3.5 and <= 3.8).

**Comment by elliottslaughter** [comment] 2016-12-08 23:11
Alternatively, if you have Homebrew you should be able to do something like:

```
brew install pypy homebrew/versions/llvm35
```

**Comment by sierrakn** [comment] 2016-12-09 02:12
I had some issues updating Homebrew on OSX Sierra, but I did and I updated
llvm and now Regent is working! Thank you for the help.
However, whenever I try to run an example program I get this error:
"/legion/runtime/legion/legion_config.h:21:10: fatal error: 'limits.h' file
not found"
I thought about changing it to climits but since I shouldn't need to edit
the code I assume there's something wrong with my paths?

On Thu, Dec 8, 2016 at 3:11 PM Elliott Slaughter <notifications@github.com>
wrote:

Alternatively, if you have Homebrew you should be able to do something like:

brew install pypy homebrew/versions/llvm35

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/StanfordLegion/legion/issues/212#issuecomment-265883902>,
or mute the thread

**Comment by elliottslaughter** [comment] 2016-12-09 06:36
It needs to be `limits.h` rather than `climits` because that part of the code is pure C (not C++).

We have regression tests on Travis, but those seem to still be on 10.11 so it's possible this is an issue with 10.12; or it could be a configuration issue on your end. I do seem to recall that Homebrew's LLVM broke when I installed it to a directory other than `/usr/local`. So if you have a non-standard install directory for Homebrew that might be something to try.

**Comment by sierrakn** [comment] 2016-12-09 07:05
OK thank you! Homebrew is in usr/local

**Comment by elliottslaughter** [comment] 2017-01-08 21:28
Hi again,

Can you update Homebrew and try again? They've deprecated the `homebrew/versions` tap, but it looks like the main `llvm` formula is working again (at least it works for me).

This ought to do it:

```
cd legion/language
rm -rf terra
brew update
brew install llvm
export LLVM_CONFIG="$(find "$(brew --prefix)"/Cellar/llvm/*/bin/llvm-config -print -quit)"
./install.py --debug
```

If that works you might want to save the `LLVM_CONFIG` variable in your `.bashrc` to preserve it for future sessions.

**Comment by sierrakn** [comment] 2017-01-09 01:11
Thanks Elliot, I actually got it working (with some help)!

**Comment by elliottslaughter** [comment] 2017-01-09 01:28
Cool. Let me know if you run into anything else. In the meantime I'm going to close this comment (but feel free to reopen or open another if you have any issues).

**Closed by elliottslaughter** 2017-01-09 01:28 UTC
