### ISSUE TITLE
Realm/Legion: Interleaved Compact Instance Layouts

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1057] opened 2021-04-17 11:44 UTC
I'm going to briefly report here a discussion about a potential new feature that I had with @lightsighter on Slack.

Imagine that a 2D stencil calculation needs to be run on a region defined on an index space formed by the union of 4 blocks as in the attached figure.
The stencil calculation for the point P (red circle) of the subregion R1 (drawn by the red line) needs to access the points Pm2, Pm1, P1, and P2 marked by the red stars with an expression that looks like `r[P].g = r[Pm2].f + r[Pm1].f + r[P].f + r[P1].f + r[P2].f`. The subregion from the aliased partition that provides support for the stencil calculation is drawn with the dashed red line.
<img width="420" alt="IndexSpace" src="https://user-images.githubusercontent.com/34253056/115111398-786d6e80-9f80-11eb-8a7f-0987ed1c1742.png">

As far as I know, there are currently two possible solutions in the legion framework that would allow to run this calculation.

The first solution uses compact sparse instances that represent the aliased partitition that spans across the blocks. The main disadvantage of this solution are:
-  Each stencil access needs a non-trivial calculation that needs to take into account the index space geometry to compute the index of the accessed point.
- The code will use the MultiAffineAccessors that are less efficient

The second solution consists of bloating the initial index space with additional points that contain the copy of the accessed stencil points for each partition and issue tasks that copy data from the source points. The main disadvantage of this procedure is that the correct enforcement of the data dependency is left to the user who needs to make sure that the copy task is correctly scheduled in the algorithm.

The proposed feature would allow the user to define a way to collocate the aliased partition with the original partition R1 as shown by the arrached figure. The idea is to allow a sort of logical mapping of the points of the aliased partition such that the stencil calculation could be executed  as `r[P].g = r[P-int2d{2,0}].f + r[P-int2d{1,0}].f + r[P].f + r[P+int2d{1,0}].f + r[P+-nt2d{2,0}].f`
<img width="394" alt="New solution" src="https://user-images.githubusercontent.com/34253056/115111766-2e858800-9f82-11eb-8275-6bbc462d9637.png">
The main advantages of this solution  are:
- the calculation of the stencil access is trivial
- the subregions in the aliased partitions can be mapped using dense instances
- the data dependency analysis is done by the runtime

@lightsighter will probably be more specific about what he had in mind to add this feature
Adding @streichler and @elliottslaughter for visibility

**Comment by elliottslaughter** [comment] 2021-04-18 04:07
Just for posterity, there is a third solution, which requires no copies and no sparse instances. That would be to use separate region requirements for the different parts of the ghost. While it's a little bit more complicated due to the interesting stencil being used here, it's our "standard" approach for these sorts of problems (e.g., in S3D).

In this example, you'd get three subregions:

 * The green box wrapped by the solid red line.
 * The blue box wrapped by the dotted red line.
 * The green box wrapped by the dotted red line.

The advantages of this approach are that you get:

 * Dense memory layout: no wasted space.
 * The stencil will be at least as fast as the MultiAffineAccessor case, potentially quite a bit faster.
 * No explicit copying in or out, data dependencies computed by Legion/Regent.
 * Requires no new Legion or Regent features.

The main disadvantage is complexity. In order to achieve maximum efficiency you need to split the inner loop into the part which is internal (accesses only points in the solid line box) and external (accesses at least one point in the dotted line boxes). You'd also have branching in the exterior loop, but I think this would still be a lot more efficient than the MultiAffineAccessor case because you have a bounded number of subregions.

**Comment by mariodirenzo** [comment] 2021-04-18 08:37
@elliottslaughter you are right that's a third option. I would also add in the disadvantages the fact that you need the complex calculation for the index of the stencil point, at least in the branches/section of the loop that apply stencils crossing the boundary of a block.

**Comment by lightsighter** [comment] 2021-04-18 08:42
> The main disadvantage is complexity.

The whole point of this issue is that we want to interleave the layouts for multiple region requirements in the same instance in a way that cannot be described in our current layout language precisely for the reason that we want to avoid this complexity in the implementation of the task. The layouts of the tiles are not the same (in this particular case we transpose dimension order and have different offsets), but they should be able to overlay in a way that you can do simpler pointer arithmetic on them inside the task body with no special branching or `%` operators required.

**Comment by elliottslaughter** [comment] 2021-04-18 16:08
@mariodirenzo I partially disagree. It's true that indexing is simplified in the copying case, or with the proposed feature. But it is *not* simplified in the MultiAffineAccessor case. I realize this isn't the primary feature under discussion here, but I want to make sure everyone understands this: MultiAffineAccessor does not simplify the indexing. Therefore, in addition to the inefficiency of the MultiAffineAccessor, you *also* need all of the if statements identified in my "third" case because you have to change the indexing equations at the boundary between pieces.

@lightsighter I realize this issue is primarily about runtime support, and I agree that the proposed feature seems plausible to implement, since it's primarily a constraint on the layout of a physical instance that allows you to perform this transformation.

I'm trying to think about the compiler support, particularly about the reasoning that would be required (in addition to what's been proposed in #878) to recover the "simple" stencil pattern on the transformed physical instance. Maybe I'm missing something, but I really cannot see how to do this in a reasonable way.

The reason for this is that the Regent programming language works entirely at the logical level. The simplification that comes from the feature proposed here exists at the physical level, which is not normally exposed to the user in Regent at all. Therefore, in the process of lowering logical to physical, the compiler has to "un-apply" all this fancy index math (and branches!) to figure out what's "really" going on, and then re-apply it at the physical level to map it into the space of the physical instances. That seems really, really hard to me.

We could contemplate exposing the physical level directly in Regent, but it's not entirely obvious to me what that would mean either, or whether we'd really want to do that, because it is a pretty significant departure from the current Regent language.

Anyway, like I said the runtime support proposed here seems reasonable to me, so I'm not trying to hold anyone back from implementing it. I just don't know how to implement anything comparable in Regent.

**Comment by mariodirenzo** [comment] 2021-04-18 16:18
> But it is not simplified in the MultiAffineAccessor case.

I agree! This disadvantage of the compact instances approach is listed in my initial post

**Comment by lightsighter** [comment] 2021-04-19 01:24
> I realize this issue is primarily about runtime support, and I agree that the proposed feature seems plausible to implement, since it's primarily a constraint on the layout of a physical instance that allows you to perform this transformation. I'm trying to think about the compiler support, particularly about the reasoning that would be required (in addition to what's been proposed in #878) to recover the "simple" stencil pattern on the transformed physical instance. Maybe I'm missing something, but I really cannot see how to do this in a reasonable way.

I didn't think @mariodirenzo was proposing to add this to Regent but he can speak for himself. We'll scope this issue to be only about the runtime support for this feature and then discussion for Regent support can go either in #878 or in a fresh issue.

**Comment by mariodirenzo** [comment] 2021-04-19 07:34
This feature would be used in specific places of the code which could use the C++ API. Including the feature in Regent would be useful but, from my point of view, we can defer this discussion to a later stage.

**Comment by lightsighter** [comment] 2022-01-25 06:25
Summarizing the agreed upon plan from the meeting today to address this issue. The plan will be a hybrid approach requiring a minor extension to the ability to create physical instances in Legion so that applications can create some scratch memory in an instance for use during the lifetime of a task. The extra padding space in the instance will be ineligible for use in mapping logical region data from Legion's perspective to avoid cases where the application or Legion might accidentally get in the other's way. HTR can use the this extra padding space to make copies of the data from logical regions at the beginning of the execution of the task and then access that data efficiently as visualized above during the rest of the application of the task. The coherence of that data is the responsibility of the application. We feel like this is the right trade-off in responsibility between the application and the runtime. It also is a fairly general solution that should also facilitate other cases where users have asked for additional scratch-pad memory in instances for the lifetime of a task such as Legate and FleCSI.

There should be no need for any Realm changes to make this happen. On the Legion front the following rather minimal changes will be required:

- [ ] The layout constraint interface will need to be extended so that applications can describe both normal and compact-sparse instances with additional padding rectangles.
- [ ] Legion's constraint checking algorithms will need to be modified to check that instances have extra padding for task variants that require it for successful execution.
- [ ] Legion's bounds checking infrastructure will need to be updated to allow application code to access data in the "padded" part of an instance without violating any privilege checks. This might require some accessor interface changes or a slightly new accessor kind.

We'll need to discuss where this goes on the priority list at an upcoming Legion meeting. Until then I'm adding the "planned" label but not assigning a milestone yet.

As an aside, @mariodirenzo owes me a reproducer for a case with a failed layout constraint satisfaction error when attempting to use a normal instance in the place of a compact-sparse instance.

**Comment by mariodirenzo** [comment] 2022-01-25 11:26
The problem was actually the opposite of what I said in the meeting. The mapper was trying to use an affine accessor to access a compact-sparse instance. It was an issue with my code.

**Comment by lightsighter** [comment] 2022-01-25 19:17
> The mapper was trying to use an affine accessor to access a compact-sparse instance.

Yes, that should be an error, so I think we're good on that front.

**Comment by lightsighter** [comment] 2022-10-06 19:02
@mariodirenzo to write down a prototype API and then ping me here with the proposal.

**Comment by mariodirenzo** [comment] 2022-10-12 16:59
My idea is that the users should have something like `MemoryScratchConstraint` which should be based on the `LayoutConstraint` class. For my application, the constructor of the constraint could be something like
```
MemoryScratchConstraint(const Point<N> minus_offset, const Point<N> plus_offset);
```
where `N` must be the same as the number of dimensions of the index space of the region requirement that will be constrained. The `minus_offset` and `plus_offset` are two constants that are subtracted/added to the lower/upper bounds of the index space of the region requirement.

For example, if the passed region requirement is based on a one-dimensional index space whose bounds are `<5...10>` and `minus_offset = Point<1>(2); plus_offset = Point<1>(3);`, the physical instance that will be utilized to map the region requirement will have the bounds  `<3...13>` whereby the first two points and the last three points are scratch space.

Does it make sense to you?

**Comment by lightsighter** [comment] 2022-10-13 09:18
I'm good with adding a new constraint kind.

The part that doesn't make sense to me is what happens when the instance isn't an `LEGION_AFFINE_*_SPECIALIZE` layout kind. If the instance layout can't be described by a rectangle of points, it's not obvious what effect the offsets will have. Do they apply to all the "pieces" of the instance? If we let Realm pick the pieces for grouping together rectangles from a sparsity map, how can the application plan for that? Alternatively, do we only want to permit scratch space on affine-only layouts?

Orthogonal question: are the offsets ever dynamic, e.g. do are they a property of the execution of the program, or are they "static" and known ahead of time when you register the task variant?

**Comment by mariodirenzo** [comment] 2022-10-13 09:41
> The part that doesn't make sense to me is what happens when the instance isn't an LEGION_AFFINE_*_SPECIALIZE layout kind. If the instance layout can't be described by a rectangle of points, it's not obvious what effect the offsets will have. Do they apply to all the "pieces" of the instance? If we let Realm pick the pieces for grouping together rectangles from a sparsity map, how can the application plan for that? Alternatively, do we only want to permit scratch space on affine-only layouts?

I do not have a use case in my application where the new constraint would be applied to sparse instances, so I would be fine with allowing this constraint only for affine pieces. However, it would make sense to me if the offset were applied to each of the "pieces" of the instance in the sparsity map.

> Orthogonal question: are the offsets ever dynamic, e.g. do are they a property of the execution of the program, or are they "static" and known ahead of time when you register the task variant?

For my use case, the constraints are completely static and are known at compile time. They can be part of the task registration even before the runtime is started.

**Comment by lightsighter** [comment] 2022-10-14 07:11
> I do not have a use case in my application where the new constraint would be applied to sparse instances, so I would be fine with allowing this constraint only for affine pieces. However, it would make sense to me if the offset were applied to each of the "pieces" of the instance in the sparsity map.

I think for now I'm leaning towards this only being applicable to instances with an affine layout kind and not any kind of sparse layout. We can relax that later if we find a compelling use case for it.

> For my use case, the constraints are completely static and are known at compile time. They can be part of the task registration even before the runtime is started.

Do you expect it will always be like that, or do you think you might ever write tasks with a runtime parameter defining the number of points? If the later, do you think you can always put an upper bound on it, or will that be too wasteful of space?

**Comment by lightsighter** [comment] 2022-10-24 09:51
So I think what I'm going to do here is to add two new members to the `SpecializedConstraint`, each of which will be a `DomainPoint` to specify the `positive_padding` and `negative_padding` on any instances that are created (e.g. how many extra points to add and subtract from the logical region bounds on each dimension. Of course they will default to zero for backwards compatibility reasons. Non-zero values will not be permitted for any kind of layout constraint other than `LEGION_AFFINE_SPECIALIZE` ( we could conceivably allow it on `LEGION_AFFINE_REDUCTION_SPECIALIZE` as well, but since you only have reduction privileges I'm not convinced yet that would actually be useful).  That should allow you both to create affine instances in the mapper which have extra padding, as well as to specify that task variants map to instances with additional padding for the execution of those task variants.

Next design question: how do you plan to access the data in this instance. Do you want/need the `FieldAccessor` class to be able to support accessing the data in "padded" instances and still consider that in-bounds when the bounds checks are turned on? Do you want to control privileges to the "padded" parts of the instance? Do you need to be able to do reductions to the padded area? Would you prefer to access the data in the padded part of the instance using the same accessor as the normal data, or do you want to make a special accessor for that?

**Comment by mariodirenzo** [comment] 2022-10-24 16:47
> Do you want/need the FieldAccessor class to be able to support accessing the data in "padded" instances and still consider that in-bounds when the bounds checks are turned on?

yes, I'd like to access the scratch space with a `FieldAccessor` and I'd like the bounds checks to be able to assess the correctness of the requested indices

> Do you want to control privileges to the "padded" parts of the instance?

What do you mean? Isn't the scratch space something that can be written and read within the context of a task and does not make sense outside the task itself?

>  Do you need to be able to do reductions to the padded area?

No, I do not

> Would you prefer to access the data in the padded part of the instance using the same accessor as the normal data, or do you want to make a special accessor for that?

I'd like to access the padded part of the data with the same accessor as the standard part. This feature is fundamental to simplifying our kernels.

**Comment by lightsighter** [comment] 2022-10-26 09:52
> What do you mean? Isn't the scratch space something that can be written and read within the context of a task and does not make sense outside the task itself?

Yes, I plan to make sure that the task has "exclusive" access to the scratch space when it runs so that no other tasks are using it at the same time (really this will be implemented more like atomic since we don't care which order tasks run that access the scratch space). I was mainly wondering if you're going to have two different "views" on to the scratch space with different accessors. It seems like the answer will be no since you want to have just one field accessor for both the region data and the scratch space. This brings me to another question: looking at the picture you drew above, the scratch space would be the "corners" in the diagram above and then you'll effectively copy data from the region parts of the instance into the scratch part and then proceed to do your computation? I fell like that is necessary for the affine accesses to be efficient during the loop.

Also, the scratch padding will need to be applied to all the fields in the instance? Is that going to be a problem?

**Comment by mariodirenzo** [comment] 2022-10-26 10:16
> This brings me to another question: looking at the picture you drew above, the scratch space would be the "corners" in the diagram above and then you'll effectively copy data from the region parts of the instance into the scratch part and then proceed to do your computation?

yes, in practice the instance that I will allocate will have a +/- 3 added to the higher/lower bound of the initial region. The efficiency of the kernel depends on having affine and contiguous accesses during the stencil calculation. Given the size of the stencil and the possible complexity of the copy patterns, the copy operation will necessarily access memories that are not contiguous and maybe even multi-affine but, considering that we copy a few data points every time, this should not affect performance too much.

> Also, the scratch padding will need to be applied to all the fields in the instance? Is that going to be a problem?

I do not think that this is a problem. The size of the padding is limited.

**Comment by lightsighter** [comment] 2022-10-26 10:35
In the picture above: what is/are the logical region(s)? Is each colored square a different logical region and we're going to build a single instance for all those regions plus the padding? If so, does the algorithm go like:

```
for r in regions:
  pad "rectangle" bounds of logical region
union bounding box(padded bounds)
```

or does it go the other way:

```
union bounding box("rectangle" bounds of all regions)
pad union bounding box
```

Either way we're going to end up with a "rectangle" instance, but we'll get different output shapes depending on which order we apply the padding with respect to computing the bounding box of the union.

**Comment by mariodirenzo** [comment] 2022-10-26 11:55
> what is/are the logical region(s)? Is each colored square a different logical region and we're going to build a single instance for all those regions plus the padding?

the only region that gets the padding is the one drawn with the solid line. The regions corresponding to the dashed boxes are utilized as sources to fill the padding space.

**Comment by lightsighter** [comment] 2022-10-31 09:36
I've started work on this feature in this branch:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/592

The only change to the user interface is a new `Domain` member on `SpecializedConstraint` called `scratch_padding`. The runtime will subtract the `lo` point off the rectangle bounds of each piece in and instance and it will add the `hi` point to the rectangle bounds of each piece. These points are therefore just relative sizes and not the actual bounds. Note this also means that all the entries in those points must also be non-negative. 

@mariodirenzo Please write a small stand-alone test case for this that has some of the behavior of your application code and commit it to the development branch. It may or may not run correctly right now as I still need validation of variant selection, management of races between tasks that want to access the scratch space at the same time, and bounds checking.

**Comment by lightsighter** [comment] 2023-03-05 02:49
The test case for this is working in the `scratchinst` branch (see merge request 592). I've asked @alexaiken to find some people or some time in a Legion meeting to do a review of the interface now that we have something that is actually working.

**Comment by lightsighter** [comment] 2023-03-11 19:08
This has been merged into the `master` branch and upstreamed to `control_replication`.

**Closed by lightsighter** 2023-03-11 19:08 UTC
Labels: enhancement, Legion, planned
