### ISSUE TITLE
Regent: OpenMP atomic "min" fails with LUA_PUC

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#881] opened 2020-06-24 12:16 UTC
This script
```
import "regent"

local C = regentlib.c
local fabs = regentlib.fabs(double)

local Npoint = 256

struct point {
   a : double
}

task find(r: region(ispace(int1d), point))
where reads(r) do
   var c99 = int(r.bounds.hi)
   var Ue = 0.356
   __demand(__openmp)
   for c in r do
      var a = r[c].a
      if (a > Ue) then c99 min= int(c) end
   end
   return c99
end

task main()
   C.printf("Start\n")
   var r = region(ispace(int1d, Npoint), point)

   for c in r do
      r[c].a = double(c)/(Npoint-1)
   end

   var Ue = 0.356
   var c99 = find(r)
   C.printf("%10.5e %10.5e %10.5e\n", r[c99-1].a, Ue, r[c99].a)

   C.printf("End\n")
end

regentlib.saveobj(main, "test.o", "object")
```
compiled
```
$LEGION_DIR/language/regent.py testChecker.rg -fopenmp 1
$CXX -o test.e test.o -L$LEGION_DIR/bindings/regent -lregent -L$HDF_ROOT/lib -lhdf5
```
provides the wrong results if it is run with
```
./test.e -ll:ocpu 1 -ll:othr 1
```

The issue reproduces only with terra on `puc_lua_master` (legion built on the master branch with `scripts/setup_env.py --llvm-version 60 --terra-url 'https://github.com/StanfordLegion/terra.git' --no-terra-cmake --terra-branch 'puc_lua_master'`) and when openmp is active

**Comment by elliottslaughter** [comment] 2020-06-24 17:13
This is probably a result of the fact that the `ULL`/`LL` types don't exist in PUC Lua: https://github.com/StanfordLegion/terra/blob/puc_lua_master/src/terralib.lua#L1692-L1698

So we work around it with `-inf` but I think that's not actually correct.

**Comment by elliottslaughter** [comment] 2020-06-29 17:59
Does the issue go away if you use a floating point data type like `double`?

**Comment by mariodirenzo** [comment] 2020-07-06 06:52
Yes, it does

**Comment by elliottslaughter** [comment] 2020-07-06 18:24
Is that an acceptable workaround for you? We could probably fix this for `int32` and smaller, but you can't actually fit an `int64` into a Lua number (at least until 5.2?) so I'm not sure how we'd even address this in that case, except via upgrading Lua.

**Comment by elliottslaughter** [comment] 2020-07-06 18:29
Actually maybe we should try out Moonjit. According to their install instructions (https://github.com/moonjit/moonjit/blob/master/INSTALL.md) they supposedly support ppc64le.

**Comment by mariodirenzo** [comment] 2020-07-06 19:00
> Is that an acceptable workaround for you? We could probably fix this for int32 and smaller, but you can't actually fit an int64 into a Lua number (at least until 5.2?) so I'm not sure how we'd even address this in that case, except via upgrading Lua.

`int32` would work fine for me. It would however be good to have an error message that warns at compile time that the operation is not supported (just to avoid spending time trying to debug the code in the future).

**Comment by elliottslaughter** [comment] 2020-07-07 23:32
I'm testing support for Moonjit here, which would also potentially make this obsolete if it works: https://github.com/terralang/terra/pull/452

**Comment by elliottslaughter** [comment] 2021-06-15 21:48
@mariodirenzo should we close this bug? I believe that Moonjit is working, and PUC Lua is no longer required even if the issue is technically still present.

**Comment by mariodirenzo** [comment] 2021-06-16 08:43
Moonjit solves the problem.
I do not know if we should close the issue. If the transition to Moonjit is definitive, then we can close the issue. If you think that Terra/Regent could go back to PUC Lua in the future, I'd keep the issue open

**Closed** 2024-03-14 19:13 UTC
Labels: bug, Regent, backlog
