### ISSUE TITLE
Regent: spurious error in index space launcher

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#524] opened 2019-04-22 17:15 UTC
Similarly to #505, the following code:
```
import "regent"

local C = regentlib.c

local Np = 10

local Nx = 2
local Ny = 2
local Nz = 2

struct Fields {
   xx : double,
   y : double,
   z : double[3]
}

__demand(__cuda, __leaf, __parallel)
task InitMesh( Mesh : region(ispace(int3d),Fields) )
where
   writes(Mesh.{xx,y,z})
do
   __demand(__openmp)
   for c in Mesh do
      Mesh[c].xx = double(c.x)/(Np-1)
      Mesh[c].y = 1.0/(Np*Np)
      Mesh[c].z = array(1.0/(Np*Np), 1.0/(Np*Np), 1.0/(Np*Np))
   end
end

__demand(__inline)
task InitStats( Mesh : region(ispace(int2d),Fields) )
where
   writes(Mesh.{xx,y,z})
do
   __demand(__openmp)
   for c in Mesh do
      Mesh[c].xx = double(c.x)/(Np-1)
   end
end

__demand(__cuda, __leaf)
task AddStats(Mesh : region(ispace(int3d),Fields),
              Stat : region(ispace(int2d),Fields),
              fact : double)
where
   reads(Mesh.{y,z}),
   reduces+(Stat.{y,z})
do
   __demand(__openmp)
   for c in Mesh do
      var c_stat = int2d{c.x,Stat.bounds.lo.y}
      Stat[c_stat].y += Mesh[c].y*fact
      Stat[c_stat].z += Mesh[c].z * array(fact,
                                          fact,
                                          fact)
   end
end

local Nr = 3

task main()
   var r = region(ispace(int3d,{Np,Np,Np}),Fields)
   var is = ispace(int2d,{Np, Nr})
   var s      = region(is,Fields)

   var cs = ispace(int2d,{Nx, max(Nr, 1)})
   var ps = partition(equal, s, cs)

   var cr = ispace(int3d,{Nx,Ny,Nz})
   var pr = partition(equal, r, cr)

   fill(r.xx, 0.0)
   fill(r.y, 0.0)
   fill(r.z, array(0.0, 0.0, 0.0))

   fill(s.xx, 0.0)
   fill(s.y, 0.0)
   fill(s.z, array(0.0, 0.0, 0.0))

   InitMesh(r)
   InitStats(s)

   for i=0,10 do
      for rake=0,Nr do
         __demand(__parallel)
         for c in cr do
            AddStats(pr[c], ps[int2d({c.x, rake})], 1.0/10)
         end
      end
   end
end

--regentlib.start(main)
regentlib.saveobj(main, "Report2.o", "object")
```
fails to compile with the error
```
Report2.rg:87: loop optimization failed: argument 2 is not provably projectable or invariant
            AddStats(pr[c], ps[int2d({c.x, rake})], 1.0/10)
```
if ``__demand(__parallel)`` is used for the loop that launches AddStats.

**Comment by elliottslaughter** [comment] 2019-04-29 18:43
This is a duplicate of #474. There is a plan for that but it has yet to be implemented.

**Comment by mariodirenzo** [comment] 2019-04-29 21:59
ok, thanks for letting me know

**Closed** 2019-04-30 05:15 UTC
Labels: Regent, duplicate
