### ISSUE TITLE
Regent - writing in tasks with "field space" type inputs

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#895] opened 2020-07-14 14:58 UTC
Redoing this issue as I solved the previous question.

If I have a task like this in regent:
```
task kernel_one(part1 : part, part2 : part)
    part1.extra_variable_1 = 1
    format.println("{}", part1.extra_variable_2)
    format.println("{}", part1.extra_variable_1)
end
```

Any side effects that occur in that task don't seem to be reflected outside of the task itself, even if I used `__demand(__inline)`. 
For example, with this calling task:
```
task pairwise_task(parts1 : region(ispace(int1d),part), parts2 : region(ispace(int1d),part)) where reads(parts1, parts2), writes(parts1, parts2, parts1.extra_variable_1) do
   for part1 in parts1 do
     for part2 in parts2 do
       parts1[part1].extra_variable_2 = 50
       kernel_one(parts1[part1], parts2[part2])
     end
   end
end
```

The output from regent with `-fpretty 1` and `__demand(__inline)` on `kernel_one` shows this task:
```
task pairwise_task($parts1 : region(ispace(int1d), part()), $parts2 : region(ispace(int1d), part()))
-- leaf (true), inner (false), idempotent (false), replicable (false)
where
  reads($parts1), reads($parts2), writes($parts1), writes($parts2), writes($parts1.extra_variable_1)
do
  for $part1 : int1d(part(), $parts1) in $parts1 do
    for $part2 : int1d(part(), $parts2) in $parts2 do
      $parts1[$part1].extra_variable_2 = float(50)
      var $part1#184 : part() = $parts1[$part1]
      var $part2#185 : part() = $parts2[$part2]
      $part1#184.extra_variable_1 = double(1)
      var $366 : float = $part1#184.extra_variable_2
      printf("%f\n", $366)
      var $367 : double = $part1#184.extra_variable_1
      printf("%f\n", $367)
    end
  end
end
```

My understanding of this is that `$part1#184.extra_variable_1 = double(1)` should be setting the variable in `parts1[part1]` as expected.
However, when I run the code (with 2 part regions of size 1, with  everything initialised to 0) like this:
```
    c.legion_runtime_issue_execution_fence(__runtime(), __context())
    pairwise_task(particle_one, particle_two)
    c.legion_runtime_issue_execution_fence(__runtime(), __context())
    format.println("{}", particle_one[0].extra_variable_2
    format.println("{}",particle_one[0].extra_variable_1)
)
```

the output from the program
is
```
50.000000
1.000000
50.000000
0.000000
```
which means the write works if its declared in the region (` $parts1[$part1].extra_variable_2 = float(50)`), but not from the access from the var declaration `$part1#184.extra_variable_1 = double(1)`. Is this `$part1` simply a copy of the reference? If so is there a way to do this? I also tried making kernel_one a terra function but without using a return value it still doesn't update.

**Comment by elliottslaughter** [comment] 2020-07-22 22:55
Arguments in Regent, aside from regions, are always pass-by-value. That means when you declare:

```
task kernel_one(part1 : part, part2 : part)
```

There's no way to modify `part1` or `part2` inside this task---and that is true whether you inline it or not.

If you really need to _modify_ values, you would need to use metaprogramming:

```
function kernel_one(part1, part2)
  return rquote
    part1.extra_variable_1 = 1
  end
end
```

And then note that when you call it, you have to use the `[]` operator:

```
task pairwise_task(parts1 : region(ispace(int1d),part), parts2 : region(ispace(int1d),part)) where reads(parts1, parts2), writes(parts1, parts2, parts1.extra_variable_1) do
   for part1 in parts1 do
     for part2 in parts2 do
       parts1[part1].extra_variable_2 = 50
       [kernel_one(rexpr parts1[part1] end, rexpr parts2[part2] end)]
     end
   end
end
```

Does that make sense?

**Comment by LonelyCat124** [comment] 2020-07-23 08:57
Yeah, I'd come to a similar idea myself but instead as I was generating the `pairwise_task` I have:
```
function generate_symmetric_pairwise_task( kernel_name )
local parts1 = regentlib.newsymbol(region(ispace(int1d),part), "parts1")
local parts2 = regentlib.newsymbol(region(ispace(int1d),part), "parts2")
local part1 = regentlib.newsymbol("part1")
local part2 = regentlib.newsymbol("part2")

local interaction = kernel_name(part1, part2)

local task pairwise_task(parts1 : region(ispace(int1d),part), parts2 : region(ispace(int1d),part))
....
   for [part1] in [parts1] do
     for [part2] in [parts2] do
      [interaction]
    end
  end
end
return pairwise_task
```

Is there much difference between predeclaration of symbols like I've done vs just calling the kernel inline in terms of the code produced? My understanding of the symbol creation is that whenever I use `[parts1]` it is replaced by the string in `newsymbol` declaration (so `parts1` in this case), which has the type defined, or the type is worked out by Regent if its not defined, is that right?

**Comment by LonelyCat124** [comment] 2020-07-23 14:07
Ok I think I worked out why mine is bad (and a further question on why it worked for a simple case).
It works fine for a simple thing, e.g. `[part1].count = [part1].count + 1`, but stopped working once I had anything more, e.g.
```
  [part].v_full_x = [part].v_full_x + ([part].accel_x * timestep)
  [part].v_full_y = [part].v_full_y + ([part].accel_y * timestep)
```

I assume this is because the `[part]` is replaced by `part1`, which should be an int1d element of the ispace, not the reference to the particle region itself. Your implementation would just "paste" the correct symbol into the function instead?
Why did this work for the simpler function?

**Comment by elliottslaughter** [comment] 2020-07-23 16:57
The predeclaration of the symbols is fine. You should be able to skip the type declarations since they will be inferred if they are not specified.

I think in order to make the interaction work, you'll need something like:

```
local interaction = kernel_name(rexpr parts1[part1] end, rexpr parts2[part2] end)
```

I'm not sure what to tell you about why the other version worked, as the `part1`/`part2` variables should be immutable and therefore throw an error if you attempt to assign to one of them.

Note that `[]` is technically unnecessary when you have a simple expression like `part1`. The place where it's necessary is when you're doing a more complicated compile-time evaluation like `[f(part1)]` (runs `f` at compile time and splices in the resulting expression).

**Comment by LonelyCat124** [comment] 2020-07-29 12:50
Rather than opening more issues for what is likely my errors, I have a quick one with comparisons of values in ispaces

I have a task:
```
task self_redo_density( parts : region(ispace(int1d), part), subset : partition(disjoint, parts, ispace(int1d)), space : region(ispace(int1d), space_config) )
   where reads(parts, space), writes(parts) do
   var no_redo = int1d(1)
   var redo = int1d(0)
   for part1 in subset[redo].ispace do
     for part2 in parts.ispace do
       --Check its not the same particle
       if(part1 ~= part2) then
        --Do some stuff
       end
     end
  end
```


When I try to call regent on this file, I get an error:
```
/home/aidan/Legion/legion/language/src/regent/type_check.t:3184: Errors reported during typechecking.
src/interactions/Gadget2SPH/tasks.rg:85: type mismatch between int1d($17645) and int1d($17646)
       if(part1 ~= part2) then
```
Can I not compare int1ds from different ispaces (even when one is a partition of the other? I want to check that I'm not performing an operation on a particle with itself.

**Comment by elliottslaughter** [comment] 2020-07-29 23:41
Can you try `if(int1d(part1) ~= int1d(part2))`? I.e. you can cast `int1d(R)` to `int1d` and then compare that.

**Comment by LonelyCat124** [comment] 2020-07-30 13:02
Yeah, that works fine (at least for compilation, not yet at a point I can test the function yet I think)

**Comment by LonelyCat124** [comment] 2020-08-05 12:53
Back with another metaprogramming issue, apologies.

With the approach I have, there's a bunch of "boilerplate" code that at current the user would have to write, but realistically is dependent on the initial conditions but otherwise the same code regardless of what they do, so I want to abstract it and create that code using metaprogramming.

What I have at current is (similar to this cut down version):
```
import "regent"

format = require("std/format")
local particle_region = regentlib.newsymbol("particle_region")

function initialisation_function(particle_array)

local init_string = rquote
var particles_space = ispace(int1d, 9)
var [particle_array] = region(particles_space, int)

end
return init_string
end


task main()

format.println("HELLO")
[initialisation_function(particle_region)]

end

regentlib.start(main)
```

The code works fine, unless there is any regent code before the `[initialisation_function(...)]`, in which case I get this error at compile time:
```
/home/aidan/Legion/legion/language/src/regent/specialize.t:104: Errors reported during typechecking.
test.rg:20: unable to specialize lua function (use terralib.cast to explicitly cast it to a terra function type)
[initialisation_function(particle_region)]
                       ^

stack traceback:
        [C]: in function 'error'
        /home/aidan/Legion/legion/language/terra/src/terralib.lua:390: in function 'finishandabortiferrors'
        /home/aidan/Legion/legion/language/src/common/report.t:56: in function 'error'
        /home/aidan/Legion/legion/language/src/regent/specialize.t:104: in function 'expr'
        /home/aidan/Legion/legion/language/src/regent/specialize.t:619: in function 'expr'
        /home/aidan/Legion/legion/language/src/regent/specialize.t:588: in function 'expr'
        /home/aidan/Legion/legion/language/src/regent/specialize.t:1823: in function 'stat'
        /home/aidan/Legion/legion/language/src/regent/specialize.t:1520: in function 'block'
        /home/aidan/Legion/legion/language/src/regent/specialize.t:2104: in function </home/aidan/Legion/legion/language/src/regent/specialize.t:2083>
        /home/aidan/Legion/legion/language/src/regent/passes.t:59: in function </home/aidan/Legion/legion/language/src/regent/passes.t:57>
        test.rg:16: in main chunk
```

The issue with this behaviour is that I'd hope to do the same strategy for the initialisation and the finalisation (i.e. file input nad output) of the program (move as much away from the user as possible) with as few restrictions as possible as to the surrounding  code. I also tried without predeclaring the symbol and had the same issue (and also without predeclaration those symbols would not be visible inside the main task when not using the print statement before that blocks metaprogramming). I also tried declaring 
`local init = initialisation_function(particle_region)` and using `[init]` instead and had a slightly different error with the prior statement:
```
/home/aidan/Legion/legion/language/src/regent/specialize.t:153: Errors reported during typechecking.
test.rg:30: unable to specialize quoted statement as an expression
[init]
```

The error occurred with basically any preceding code more complicated than arithmetic. The only major difference to the previous examples above is the lack of surrounding "generating function", but I tried that as well and it made no difference. I have a feeling I'm doing something obvious wrong but I can't work it out, any ideas?

**Comment by elliottslaughter** [comment] 2020-08-06 23:58
This is a known ambiguity in the Regent parser (can't find an issue for it right now). You can fix it by terminating the previous line with a `;`.

The problem is you can't tell whether `a [x]` is an array access or an expression followed by an escape. Terra hacks this by detecting a newline and turning it into a `;`, but that seems like a hack to me and I don't really want to implement it.

**Comment by elliottslaughter** [comment] 2021-06-15 21:46
@LonelyCat124 are all your problems in this issue resolved?

**Comment by LonelyCat124** [comment] 2021-06-16 09:40
I think yes (via the workarounds you suggested).

I'm not sure if the typechecker still fails on int1d comparisons from different index spaces but I just cast them to int1d I believe:
```
/home/aidan/Legion/legion/language/src/regent/type_check.t:3184: Errors reported during typechecking.
src/interactions/Gadget2SPH/tasks.rg:85: type mismatch between int1d($17645) and int1d($17646)
       if(part1 ~= part2) then
```

**Comment by elliottslaughter** [comment] 2021-06-16 13:45
I think it would still complain on that code, but as you said you can cast away the region bounds on the `int1d`.

**Closed by elliottslaughter** 2021-06-16 13:45 UTC
Labels: Regent, backlog, bug
