### ISSUE TITLE
Regent: Support for intXd with X > 3

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#467] opened 2019-01-11 18:10 UTC
Legion and Regent now have support for a variable number of index space dimensions, and this support has been ported to the C interface.

What remains is to use this feature to extend Regent's int2d/3d to more dimensions. This should be straightforward, as most operations on int2d/3d are already handled uniformly, by mapping over the structs' fields.

Mainly, someone needs to run through the code looking for uses of hardcoded numbers for the maximum number of dimensions, and replace them with the appropriate compile-time constant (e.g. this assertion https://github.com/StanfordLegion/legion/blob/8474f232dd50f68b26c77009e757f098766a73ad/language/src/regent/std.t#L1891 and this for-loop https://github.com/StanfordLegion/legion/blob/8474f232dd50f68b26c77009e757f098766a73ad/language/src/regent/std.t#L2123).

Also see #466.

**Comment by elliottslaughter** [comment] 2019-01-16 18:34
I have an initial patch that fixes this (not pushed yet), but right now Legion doesn't even compile with `CC_FLAGS=-DLEGION_MAX_DIM=4`, so even if I push it you won't be able to do anything until that is fixed.

**Comment by elliottslaughter** [comment] 2019-01-16 18:35
Compile error:

```
/home/elliott/legion/runtime/legion/legion_c.cc:3912:1633:   required from here
/home/elliott/legion/runtime/realm/dynamic_templates.h:183:50: error: no type named ‘TYPE’ in ‘struct Realm::DynamicTemplates::IntList<1, 3>::ERROR_INT_NOT_IN_LIST<4>’
  typedef typename ERROR_INT_NOT_IN_LIST<N>::TYPE TYPE;
                                                  ^
```

**Comment by elliottslaughter** [comment] 2019-01-16 21:49
Well, my patch is in. There is now a `-flegion-dim` flag you can use to tell Regent about the value of `LEGION_MAX_DIM`. It's now up to @lightsighter to get the runtime to pass when `LEGION_MAX_DIM` is something other than 3.

**Comment by lightsighter** [comment] 2019-01-17 07:57
This is not a bug. As I said in my original email, you have to update REALM_MAX_DIM in sync with LEGION_MAX_DIM. There is no coupling of them for obvious reasons. If you want I can make a static assertion if LEGION_MAX_DIM > REALM_MAX_DIM which will cause a compile error when you try to build Legion. Assigning back to @elliottslaughter to respond about what he thinks is best.

**Comment by lightsighter** [comment] 2019-01-17 18:48
That sounds good to me. I think I'll add the static assertion too just so people will get an better error message.

**Comment by elliottslaughter** [comment] 2019-01-17 19:57
@manopapad Please pull master and try this:

```
MAX_DIM=4 ./install.py --debug
./regent.py examples/circuit.rg -flegion-dim 4
```

**Comment by manopapad** [comment] 2019-01-17 22:35
That works. Presumably we also want to have some testcases with int4d etc.

**Comment by elliottslaughter** [comment] 2019-08-20 18:05
Closing, this has been supported for a while.

**Closed by elliottslaughter** 2019-08-20 18:05 UTC
Labels: Regent
