### ISSUE TITLE
All tests fail in legion-18.05.0 with "invalid processor handle" on x86_64 on Fedora29

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#398] opened 2018-06-01 17:08 UTC
All tests fail on x86_64 (and ppc64le):
```
0% tests passed, 24 tests failed out of 24
Total Test time (real) =  18.46 sec
The following tests FAILED:
	  1 - attach_file (Child aborted)
	  2 - circuit (Child aborted)
	  3 - dynamic_registration (Child aborted)
	  4 - ghost (Child aborted)
	  5 - ghost_pull (Child aborted)
	  6 - realm_saxpy (Child aborted)
	  7 - realm_stencil (Child aborted)
	  8 - spmd_cgsolver (Child aborted)
	  9 - virtual_map (Child aborted)
	 10 - attach_2darray (Child aborted)
	 11 - attach_array_daxpy (Child aborted)
	 12 - hello_world (Child aborted)
	 13 - tasks_and_futures (Child aborted)
	 14 - index_tasks (Child aborted)
	 15 - global_vars (Child aborted)
	 16 - logical_regions (Child aborted)
	 17 - physical_regions (Child aborted)
	 18 - privileges (Child aborted)
	 19 - partitioning (Child aborted)
	 20 - multiple_partitions (Child aborted)
	 21 - custom_mapper (Child aborted)
	 22 - attach_file_mini (Child aborted)
	 23 - test_stl (Child aborted)
	 24 - rendering (Child aborted)
```
with:
```
rendering: /builddir/build/BUILD/legion-legion-18.05.0/runtime/realm/runtime_impl.cc:2451: Realm::ProcessorImpl* Realm::RuntimeImpl::get_processor_impl(Realm::ID): Assertion `0 && "invalid processor handle"' failed.
```
([Details](https://github.com/StanfordLegion/legion/files/2063550/build.log.txt))

Surprisingly the same tests pass on i686, ppc64 and s390x!

(https://bugzilla.redhat.com/show_bug.cgi?id=1585174)

**Comment by streichler** [comment] 2018-06-01 17:30
That's odd.  Do you have a docker container that reproduces this?  If not, I'll see about spinning up a VM.

Also, can you confirm whether ppc64le is broken (as the top of the post says) or passing (as the bottom says)?

**Comment by junghans** [comment] 2018-06-01 18:34
Sorry typo, x86_64, ppc64le and aarch64 is broken: https://koji.fedoraproject.org/koji/taskinfo?taskID=27351208

**Comment by junghans** [comment] 2018-06-01 20:46
Something like:
```Dockerfile
FROM fedora:rawhide
RUN dnf install -y gasnet-devel git cmake redhat-rpm-config gcc-c++ gdb hwloc-devel make
RUN git clone https://github.com/StanfordLegion/legion.git
WORKDIR legion/build
ENV CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
ENV CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
ENV LDFLAGS='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed'
RUN cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DLegion_USE_HWLOC=ON -DLegion_BUILD_EXAMPLES=ON -DCOMPILER_SUPPORTS_MARCH=OFF -DCOMPILER_SUPPORTS_MCPU=OFF -DLegion_BUILD_TESTS=ON -DLegion_BUILD_TUTORIAL=ON -DLegion_ENABLE_TESTING=ON ' ' -DLegion_USE_GASNet=OFF ..
RUN make
RUN make test
```

**Comment by streichler** [comment] 2018-06-01 23:48
@junghans can you try applying the patch we discussed in #350?  It doesn't look like I ever committed that to the actual repo...  :(

**Comment by junghans** [comment] 2018-06-02 13:32
The patch was actually in [there](https://src.fedoraproject.org/rpms/legion/blob/master/f/gcc-8.patch), I just dropped it assuming you had merged it, it seems to work now.

**Comment by junghans** [comment] 2018-06-02 15:52
Hmm as in #350, the `circuit` test still fails on ppc64 and s390x plus aarch64:
```
 2/25 Test  #2: circuit ..........................***Exception: Child aborted  1.12 sec
[0 - 7fff4ef3ece0] {3}{circuit}: circuit settings: loops=2 pieces=4 nodes/piece=2 wires/piece=4 pct_in_piece=95 seed=12345
[0 - 7fff4ef3ece0] {3}{circuit}: Initializing circuit simulation...
/usr/include/c++/8/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = Realm::Rect<1, long long int>; _Alloc = std::allocator<Realm::Rect<1, long long int> >; std::vector<_Tp, _Alloc>::const_reference = const Realm::Rect<1, long long int>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
*** Caught a fatal signal: SIGABRT(6) on node 0/1
```

**Comment by lightsighter** [comment] 2018-06-02 17:46
@junghans Can you get a backtrace for the circuit failure?

**Comment by junghans** [comment] 2018-06-02 20:18
Not easily!

**Comment by junghans** [comment] 2018-06-03 17:56
@nmorey can you confirm the same on OpenSuse?

**Comment by nmorey** [comment] 2018-06-04 09:39
@junghans It works for Tumbleweed as it is still using gcc 7.
You can monitor the status of the latest master here: https://build.opensuse.org/package/show/science:HPC:Head/legion

This is auto updated regularly to check this kind of error. (It is NOT to be used apart from testing purposes)

**Comment by junghans** [comment] 2018-06-04 12:12
@nmorey could you test this in `devel:gcc` with gcc-8?

**Comment by streichler** [comment] 2018-06-04 18:57
@junghans can you build and run with `REALM_BACKTRACE=1` in the environment?  I can't reproduce the circuit failure in my docker container.

**Comment by streichler** [comment] 2019-06-16 17:28
#409 is closed, so closing this one too

**Closed by streichler** 2019-06-16 17:28 UTC
