### ISSUE TITLE
Regent: potential bug in codegen

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#558] opened 2019-06-26 16:27 UTC
Regent fails to compile the following script
```
import "regent"

local C = regentlib.c

local Np = 10

local Nx = 2
local Ny = 2
local Nz = 2

struct Fields {
   y : double,
}

task doStuff(r : region(ispace(int3d),Fields),
             s : region(ispace(int2d),Fields))
end

task main()
   var r = region(ispace(int3d,{Np,Np,Np}),Fields)
   var s = region(ispace(int2d,{Np,Np}),Fields)

   var cr = ispace(int3d,{Nx,Ny,Nz})
   var pr = partition(equal, r, cr)

   var cs = ispace(int2d,{Nx,Ny})
   var ps = partition(equal, s, cs)

   fill(r.y, 0.0)
   fill(s.y, 0.0)

   for c in cr do
--      C.printf("%d %d %d\n", c.x,c.y,c.z)
      doStuff(pr[c], ps[int2d{c.x,c.y}])
   end
end

regentlib.start(main)
```
with the following error
```
src/terralib.lua:1124: Errors reported during typechecking.
/home/ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:2880: invalid conversion from anon$107 to legion_domain_point_t
      runtime, parent, index)
                           ^
/home/ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:2880: user-defined cast failed: src/terralib.lua:1154: Errors reported during typechecking.
/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:3310: invalid conversion from int64 to int64[4]
              from_field_type, to_field_type, `([v].["_" .. tostring(i)]))
                                                 ^

stack traceback:
	[C]: in function 'error'
	src/terralib.lua:388: in function 'finishandabortiferrors'
	src/terralib.lua:3325: in function 'typecheck'
	src/terralib.lua:1154: in function 'definequote'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:1246: in function 'fn'
	src/asdl.lua:18: in function 'map'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:3305: in function </home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:3288>
	[C]: in function 'xpcall'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:2880: Errors reported during invoking __cast
      runtime, parent, index)
                           ^
	src/terralib.lua:2239: in function 'insertcast'
	src/terralib.lua:2614: in function 'trylist'
	...
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:2872: in function 'make_partition_projection_functor'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:3199: in function 'expr_call_setup_partition_arg'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:8910: in function 'fn'
	src/asdl.lua:18: in function 'block'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:10621: in function 'compile_thunk'
	...ctrsp-2018/mariodr/legion/language/src/regent/std_base.t:1369: in function 'complete'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4193: in function </home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4191>
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4195: in function 'compile_tasks_in_parallel'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4310: in function 'start'
	Report4.rg:38: in main chunk
      runtime, parent, index)
                           ^

stack traceback:
	[C]: in function 'error'
	src/terralib.lua:388: in function 'finishandabortiferrors'
	src/terralib.lua:3319: in function 'typecheck'
	src/terralib.lua:1124: in function 'defineobjects'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:2872: in function 'make_partition_projection_functor'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:3199: in function 'expr_call_setup_partition_arg'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:8910: in function 'fn'
	src/asdl.lua:18: in function 'block'
	.../ctrsp-2018/mariodr/legion/language/src/regent/codegen.t:10621: in function 'compile_thunk'
	...ctrsp-2018/mariodr/legion/language/src/regent/std_base.t:1369: in function 'complete'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4193: in function </home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4191>
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4195: in function 'compile_tasks_in_parallel'
	/home/ctrsp-2018/mariodr/legion/language/src/regent/std.t:4310: in function 'start'
	Report4.rg:38: in main chunk
```

If the statement `C.printf("%d %d %d\n", c.x,c.y,c.z)` is inserted in the loop, the error disappears.

**Comment by elliottslaughter** [comment] 2019-06-27 16:13
What Legion commit are you on, and what flags did you use to run this? I'm not able to reproduce locally.

**Comment by mariodirenzo** [comment] 2019-06-27 16:56
I'm on commit `be6e2178` of the `control_replication` branch.
Legion is compiled with `MAX_DIM=4 USE_CUDA=0 USE_OPENMP=1 USE_GASNET=1 USE_HDF=1 scripts/setup_env.py --llvm-version 38`.
The code is executed with `regent.py Report4.rg -fflow 0 -fbounds-checks 1 -flegion-dim 4`

**Comment by elliottslaughter** [comment] 2019-06-27 17:07
Fascinating, I think this is the first bug I've seen that reproduces only with RDIR *disabled*.

I can reproduce on master with `-fflow 0` and no other flags or build-time options.

**Comment by elliottslaughter** [comment] 2019-06-27 17:34
Fixed in master, but wait for a merge into control_replication before you test.

**Comment by elliottslaughter** [comment] 2019-06-27 17:35
Ok, merge complete. Please test.

**Comment by mariodirenzo** [comment] 2019-06-27 17:51
The reproducer works.
I'm testing it also in the complete code. I'll let you know as soon as it finishes compiling

**Comment by mariodirenzo** [comment] 2019-06-27 19:45
The fix works also in the bigger code. Thanks!

**Closed** 2019-06-27 20:48 UTC
Labels: Regent, bug
