### ISSUE TITLE
Realm: scalable machine config broadcast

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1577] opened 2023-10-27 21:49 UTC
Realm currently uses an all-to-all communication pattern to implement the announcements which share the machine config between nodes. This is (a) potentially a startup performance issue, and (b) causes freezes on certain networks such as Slingshot 11 that struggle with "nonscalable" communications.

Point (b) is currently resulting in a freeze on Frontier at 600+ nodes, which leaves multiple ranks stuck at this line:

https://github.com/StanfordLegion/legion/blob/d4cef06c68574f1089e5cb7d1eebe4a6b16b9bac/runtime/realm/runtime_impl.cc#L1910

I will pursue other ways to work around this on the network side, but it would be best if we can simultaneously work on improving this in Realm.

**Comment by apryakhin** [comment] 2023-11-01 17:03
This potentially can overlap with us working on a "scalable" barrier tree broadcast now

**Comment by muraj** [comment] 2023-11-02 00:20
Yeah, our current mechanism for doing the announcements within realm is to issue a message for each memory, affinity, and processor to each rank for the application.  This can easily be O(n^2) messages pending before we get around to receiving them from the receive buffer.  I'm not sure how gasnetex handles this.  One easy solution is to forego the use of active messages entirely in the announcement stage of Realm's initialization and instead just batch up the information and let the network backend do an all_gather on the data, or just do N broadcasts for this data.  This would greatly simplify the announcement code.  We could regain any overlap by using the asynchronous paths for allgather/broadcast.

I'll try prototyping this locally and see what happens.  I could use any pointers on how to perform an all_gather in gasnet1 and gasnetex though.

**Comment by lightsighter** [comment] 2023-11-02 02:28
> I could use any pointers on how to perform an all_gather in gasnet1 and gasnetex though.

There's definitely no all-gather in gasnet1. Parts of the extended API probably have what you want for doing [bulk puts/gets](https://gasnet.lbl.gov/docs/gasnet.html#Blocking-memory_002dto_002dmemory-Transfers), but you'll need to do the "butterfly" yourself with those point-to-point operations. The new GASNetEx API has the concepts of teams for doing collective operations. I don't think they have an all-gather primitive for teams though yet, although I could have just missed it.

**Comment by eddy16112** [comment] 2023-11-02 02:55
Looks like all network modules have the implementation of `bcast` and `gather` https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/gasnet1/gasnet1_module.cc#L746-758. If they are optimized, maybe we can simply do:
```
gather(root=0, value)
bcast(root=0, value)
```

**Comment by muraj** [comment] 2023-11-02 03:42
Hm, the issue is that each rank could have a very different number of things to broadcast to all the other ranks (the size of 'value' is not fixed across all ranks), so a simple "gather(root=0, value); bcast(root=0, value);" wouldn't be enough.

Maybe instead, we could send direct messages to the root and have the root collect them and broadcast the entire bundle out to everyone (likely in several pieces at a time probably since MPI limits the buffer to 2^31 bytes)?  That would reduce the number of messages from O(n^2) to O(n*k) where k is the number of pieces at least?  This would be idea #1.

The other idea is to do 2*N bcasts() of the size and then data for each node, but I worry the extra synchronization for each broadcast for each node will be prohibitively slow.  This would be idea #2

The last idea is to try to pick a part the various ActiveMessage::commit implementations and provide a way to recognize when all peers in the target network module are being sent to and do an broadcast here.  The issue with that is the ActiveMessage::commit functions are pretty complex for gasnet1 and gasnetex, it would take a fairly large effort to even understand what's going on here, let alone try to modify it for this optimization I think.  Even if we decided to do it, this optimization path would only really be triggered for the announcement during initialization, where we have to wait for all the data anyway (we currently spin wait for it), so hte asynchronous nature of the ActiveMessage is somewhat lost.  This would be idea #3.

Right now, I'm kind of leaning on idea #1, just accumulate all the active messages that we already have to Realm's node 0, then broadcast the accumulated active message out to everyone.  It modifies the fewest code paths I think, since I can reuse the active message paths we already have.

**Comment by elliottslaughter** [comment] 2023-11-02 03:48
I admit I don't appreciate the complexities here, but I thought the hypercube algorithm for all-gather is well understood. What's the roadblock to implementing it?

There's a set of lecture slides that describe it, starting at slide 21 (though it refers back to other material introduced in the slides): https://cseweb.ucsd.edu/classes/fa12/cse260-b/Lectures/Lec14.pdf

**Comment by elliottslaughter** [comment] 2023-11-02 03:52
Here's a paper that describes two common algorithms for all-gather (see Section 4.1): https://web.cels.anl.gov/~thakur/papers/ijhpca-coll.pdf

**Comment by muraj** [comment] 2023-11-02 04:41
@elliottslaughter like I mentioned, the items for each node are not necessarily of uniform size, which I think makes this a little more complex since you need to first send the total size to the receiver before sending the buffer for each step of whatever algorithm we do, and we can't just send a fixed very large sized buffer because we don't know how big is "big enough" without even more communication between nodes and we could also be sending a lot more than we need.  I was trying to leverage the networking module's bcast and gather functions as much as possible in order to rely on their implementation to "do the right thing" instead of having to implement the algorithm ourselves, since some algorithms are more suited to specific topologies over others (for example, shared memory vs. NIC messages).

**Comment by eddy16112** [comment] 2023-11-02 04:55
@muraj I feel like #1 might be better. Assuming the bottleneck of Frontier is 1-to-N, then as long as the bcast from network is not using the flat tree algorithm, we won't hit the case of 1-to-N. 

BTW, gatherv is able to handle uniform size buffer, but not sure if gasnet/gasnetex has a gatherv implementation.

**Comment by muraj** [comment] 2023-11-02 05:12
Yeah, I was thinking about using all_gatherv, but I didn't see anything similar, and since we had to implement our own gather using broadcast for gasnetex, and because this is specifically a gasnetex reported issue, I wanted to make sure I had an algorithm in place for it.

**Comment by muraj** [comment] 2024-07-24 17:54
This has been implemented and is available today, with proper fallbacks in place.  Moving this to closed, please re-open if there are additional items necessacary.

**Closed by muraj** 2024-07-24 17:54 UTC
Labels: ExaFEL
