### ISSUE TITLE
Xcode guard malloc check crashes startup

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#240] opened 2017-04-24 23:42 UTC
Xcode does us the favor of refusing to make large mallocs unless the environment var MALLOC_PERMIT_INSANE_REQUESTS is set (to any value).
This only happens when the Xcode memory diagnostics are turned on.
If this env var is not set and diags are on we see output like this after calling start()

GuardMalloc[prototype0-7489]: Allocations will be placed on 16 byte boundaries.
GuardMalloc[prototype0-7489]:  - Some buffer overruns may not be noticed.
GuardMalloc[prototype0-7489]:  - Applications using vector instructions (e.g., SSE) should work.
GuardMalloc[prototype0-7489]: version 109
prototype0(7489,0x1017543c0) malloc: protecting edges
prototype0(7489,0x1017543c0) malloc: enabling scribbling to detect mods to free blocks
[0 - 1017543c0] {4}{numa}: numa support not available in system
GuardMalloc[prototype0-7489]: Attempting excessively large memory allocation:  536871167 bytes
GuardMalloc[prototype0-7489]: If you really wanted to allocate so much memory, launch your executable with the environment variable MALLOC_PERMIT_INSANE_REQUESTS set to any value to circumvent this check.
GuardMalloc[prototype0-7489]: Explicitly trapping into debugger!!!

**Comment by lightsighter** [comment] 2017-04-25 03:40
I'm guessing this is the allocation for the "system" memory by Realm.  Can you get a backtrace from the debugger on the malloc that it is unhappy with?

**Comment by jiazhihao** [comment] 2017-04-25 05:36
@aheirich, what's the command line you used to start Legion? I guess part of the allocated memory is used as intermediate buffers for multi-hop data transfers.

**Comment by streichler** [comment] 2017-04-25 10:38
Alan and I dug into this yesterday.  It is indeed the system memory allocation, and the problem is that somehow the xcode people think 512MB is an "insane" amount of memory to request in a single call.  My plan is to set the environment variable during runtime init.

**Comment by streichler** [comment] 2017-08-25 16:28
@aheirich Can I ask you to try to reproduce this failure?  Setting the environment variable during Realm startup is easy enough, but I want to make sure it actually solves the problem.

**Comment by streichler** [comment] 2017-09-01 16:15
@aheirich Another ping on this...

**Comment by aheirich** [comment] 2017-09-01 17:05
Sorry about the delay, I forgot about this issue.
I just tried it again, running visualization test with -ll:csize 4000
and I got this result when the malloc debug features were all enabled in Xcode:

GuardMalloc[visualization_reductions-2404]: If you really wanted to allocate so much memory, launch your executable with the environment variable MALLOC_PERMIT_INSANE_REQUESTS set to any value to circumvent this check.
GuardMalloc[visualization_reductions-2404]: Explicitly trapping into debugger!!!

So it seems the problem is still there.

**Comment by streichler** [comment] 2017-09-01 18:17
@aheirich and I performed a few experiments, and it seems that this environment variable needs to be set before the process starts.  Even adding it to the environment variable list in a global variable's constructor is insufficient.

So the plan for now is to just update the macOS build notes and hope that people read the documentation.  Reassigning the bug to me.

**Comment by streichler** [comment] 2019-09-14 18:57
Nobody's complained about this in ages, so I'm closing it out.

**Closed by streichler** 2019-09-14 18:57 UTC
Labels: enhancement
