### ISSUE TITLE
Regent: Issues compiling regent for multi node systems.

### ISSUE THREAD

**Issue by Nischay-Pro** [StanfordLegion/legion#885] opened 2020-07-03 05:19 UTC
Hello!

@rupanshusoi and I have been trying to get Regent up and running on our 10 node system and are running into a few issues. Our nodes are using an AMD Epyc 7542 connected via infiniband. We've install Centos 8.2 on all the nodes.

We've tried compiling it using the `setup_env.py` script provided in the scripts folder. 

We passed the following environment variable
`CONDUIT=ibv CC=gcc CXX=g++ python3 ./setup_env.py`

Our current system uses Spack as a HPC library package manager. We tried using both Centos 8.3.1 (Shipped with Centos) and 9.3.0 (Built via Spack) but the script fails midway throwing the following error. 

> /bin/ld: skipping incompatible /lib/librt.so when searching for -lrt
/bin/ld: skipping incompatible /lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /lib/libdl.so when searching for -ldl
/bin/ld: skipping incompatible /lib/librt.so when searching for -lrt
/bin/ld: skipping incompatible /lib/libm.so when searching for -lm
/bin/ld: skipping incompatible /lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/bin/ld: skipping incompatible /lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /lib/libc.so when searching for -lc
/bin/ld: skipping incompatible /lib/libgcc_s.so.1 when searching for libgcc_s.so.1

Furthermore we've tried separately building Gasnet with ibv and linking to Regent which builds successfully but throws a lot of errors on runtime. If you guys wanna have a look at this I can share more details.

**Comment by elliottslaughter** [comment] 2020-07-07 22:36
I'm not sure those messages are actual errors, could you paste the full output somewhere for us to see? Thanks.

**Comment by Nischay-Pro** [comment] 2020-07-08 05:07
I've attached the logs to this comment. Let me know if you need anymore information.

[output.log](https://github.com/StanfordLegion/legion/files/4888566/output.log)

**Comment by elliottslaughter** [comment] 2020-07-08 21:18
Did this actually fail? Can you try running `ldd bindings/regent/libregent.so`?

**Comment by Nischay-Pro** [comment] 2020-07-09 04:16
Here's the output from that.
[bindings.log](https://github.com/StanfordLegion/legion/files/4894492/bindings.log)

**Comment by rupanshusoi** [comment] 2020-07-09 06:01
@elliottslaughter Ok so it looks like the installation was indeed successful. The problem now is that launching a Regent application is too slow with `srun`, which is our job manager. The same installation of `srun` (and Slurm) works fine for the other languages we're using. 

I use `srun -p compute -n 64 --cpu-bind none python3 regent.py ...` for example to launch a 64 core run.

I don't think this is very important, but for the sake of completeness, we also get this warning
```
WARNING: 32 of 32 processes have HCAs believed to support ODP.  However, the
         corresponding software support was not found at configure time.
         Please see the README for GASNet's ibv-conduit for more info on ODP.
         To suppress this message set environment variable
         GASNET_ODP_VERBOSE=0 or reconfigure with --disable-ibv-odp
         (see ibv-conduit's README for more information).
```
I don't think this is due to a badly configured installation of GASNet because the wait times are same for even single node runs launched by `srun`. 

Please note that launching small programs with `srun` works fine, I'm only seeing this problem with our solver. Any ideas?

**Comment by elliottslaughter** [comment] 2020-07-09 14:12
Does it make any difference if you do:

`LAUNCHER="srun -p compute -n 64 --cpu-bind none" python3 regent.py test.rg -ll:cpu 62`

Also, you can use a `-v` flag to `srun` to get a more detailed summary of what it's doing. I.e., is it `srun` that's being slow (for whatever reason) or Regent?

Have you tried compiling and running Regent binaries via `regentlib.saveobj`?

**Comment by rupanshusoi** [comment] 2020-07-09 14:24
@elliottslaughter Ok so I figured out that I wasn't using the correct flags. Running this for single node runs works

`srun -p compute -c 64 python3 regent.py test.rg -ll:cpu 62` 

and gives expected performance.  Hello world for multi node runs works by doing

`srun -p compute -c 64 -n <nodes> python3 regent.py hello.rg -ll:cpu 62`. 

However the same doesn't work for my solver. I get a segfault with exit code `245`. Let me know if you would like to see a backtrace.

**Comment by elliottslaughter** [comment] 2020-07-09 14:25
Sure, what's the backtrace?

**Comment by rupanshusoi** [comment] 2020-07-09 14:26
Compiling in debug mode, give me a few minutes.

**Comment by rupanshusoi** [comment] 2020-07-09 16:29
@elliottslaughter Ok so I haven't been able to get it to segfault after recompiling. Either the process is hanging or taking very long to finish. Sometimes I'm able to get my solver to run for a small number of timesteps. 

I should ask, has Regent been used with Slurm before? If you know somebody who was experience with this, it might be useful to ask them what flags/configuration they use.

Passing -REALM_BACKTRACE=1 on the command line is enough to generate a backtrace right?

**Comment by rupanshusoi** [comment] 2020-07-09 16:40
To get an idea of how long it is taking, I just completed a run with `srun` and it took about 15 min, whereas if I start it directly it takes  less than 1.

**Comment by elliottslaughter** [comment] 2020-07-09 17:16
We use SLURM with `srun` all the time on a number of machines: Cori, Piz Daint, etc. We've done runs up into the thousands of nodes. Startup times are similar to MPI.

I would try pre-compiling a binary. That would take one major step of the process and get it out of the way. It also helps to make the runs more reproducible since there's no chance for non-determinism in the compiler (or rather, there is but you'll always execute the same binary everywhere).

After this I would go back to the `-v` flag for `srun` and `-level announce=2` to make sure Legion is starting up. If that indicates that the run in starting but then freezing somewhere in the middle of the run, then we're into our usual freeze detection techniques, i.e. https://legion.stanford.edu/debugging/#dump-backtraces and https://legion.stanford.edu/debugging/#dump-events.

As for the crash, I'd be extra sure to check that you get no errors in debug mode. (You don't have any `-level` flags, right?) Assume debug mode works, then I'd recompile in release mode but add `-g` to get debug symbols.

**Comment by rupanshusoi** [comment] 2020-07-09 17:22
What exactly do I do to run the binary?

**Comment by elliottslaughter** [comment] 2020-07-09 17:23
`srun ... ./my_binary -ll:cpu 62` i.e., keep all of the original flags except flags for the compiler (`-f...`) and the compiler command line itself (`python3 regent.py hello.rg`).

**Comment by rupanshusoi** [comment] 2020-07-09 18:06
I'm getting the following on trying to compile to an executable 

`/usr/bin/ld: /tmp/terra-768f95.o: undefined reference to symbol 'log10@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
`

**Comment by rupanshusoi** [comment] 2020-07-09 18:16
Also, since I don't see any errors or segfaults, just that the application is running really slow, would it be useful to see some Legion Prof output?

**Comment by rupanshusoi** [comment] 2020-07-09 18:26
I also tried running with `-level announce=2` but it looks like `srun` prints all output only when the application finishes so I can't really tell when Legion says `node ... has received all of its announcements` (assuming that is what you wanted to know).

**Comment by elliottslaughter** [comment] 2020-07-09 18:43
If you can get the application to complete, then Legion Prof would be helpful, but note that it's really better not to do Legion Prof in debug mode, so that's going to depend on whether you can get release mode working.

**Comment by elliottslaughter** [comment] 2020-07-09 18:43
> I'm getting the following on trying to compile to an executable
> 
> `/usr/bin/ld: /tmp/terra-768f95.o: undefined reference to symbol 'log10@@GLIBC_2.2.5' //lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line `

This looks like an issue with a mismatch in libraries? Are you sure you've got the right library paths for this machine?

**Comment by elliottslaughter** [comment] 2020-07-09 18:44
> I also tried running with `-level announce=2` but it looks like `srun` prints all output only when the application finishes so I can't really tell when Legion says `node ... has received all of its announcements` (assuming that is what you wanted to know).

You might have luck with `srun`'s `--output` flag to send output to a file. Alternatively, `stdbuf -o0` may help. If those don't work, I guess we're back to either Legion Prof or including timestamps in the output (so we can tell how things occurred after the fact).

**Comment by rupanshusoi** [comment] 2020-07-09 19:24
I've been testing with small numbers of subregions of my main partition, so as to limit inter-node communication. Surprisingly everything seems to be working fine with this, so I'm guessing the problem is with GASNet not being able to send messages fast enough, leading to unexpectedly long runs. 

Let me know if this makes any sense; I will only be able to get to your other suggestions in the morning.

**Comment by rupanshusoi** [comment] 2020-07-09 20:10
For the record, let me put some results here, as I understand them.

Launching application directly: 55 s
32 cores per process, 1 process, 1 node: 50 s
16 cores per process, 2 processes per node, 1 node: 1 min 44 s
16 cores per process, 1 process per node, 2 nodes: 1 min 47 s

**Comment by elliottslaughter** [comment] 2020-07-09 22:28
Can you confirm: "launching application directly" means using the same number of cores? I don't see any reason why that should be any different than running "1 process, 1 node" assuming the `-ll:cpu` value is the same... unless the core binding is off.

Can you try adding `-ll:show_rsrv` to the first two cases (direct and 1 process on 1 node). That would let us see if the binding differs.

It might also help to add `--cpu_bind verbose` so that we can compare what Realm sees with what srun thinks it's giving it.

**Comment by rupanshusoi** [comment] 2020-07-10 03:57
1. Direct launch with `-ll:cpu 32` on 1 node: 52 s

Realm output:

```
core map {
  domain 0 {
    core 0 { ids=<0> }
    core 1 { ids=<1> }
    core 2 { ids=<2> }
    core 3 { ids=<3> }
    core 4 { ids=<4> }
    core 5 { ids=<5> }
    core 6 { ids=<6> }
    core 7 { ids=<7> }
    core 8 { ids=<8> }
    core 9 { ids=<9> }
    core 10 { ids=<10> }
    core 11 { ids=<11> }
    core 12 { ids=<12> }
    core 13 { ids=<13> }
    core 14 { ids=<14> }
    core 15 { ids=<15> }
    core 16 { ids=<16> }
    core 17 { ids=<17> }
    core 18 { ids=<18> }
    core 19 { ids=<19> }
    core 20 { ids=<20> }
    core 21 { ids=<21> }
    core 22 { ids=<22> }
    core 23 { ids=<23> }
    core 24 { ids=<24> }
    core 25 { ids=<25> }
    core 26 { ids=<26> }
    core 27 { ids=<27> }
    core 28 { ids=<28> }
    core 29 { ids=<29> }
    core 30 { ids=<30> }
    core 31 { ids=<31> }
  }
  domain 1 {
    core 32 { ids=<32> }
    core 33 { ids=<33> }
    core 34 { ids=<34> }
    core 35 { ids=<35> }
    core 36 { ids=<36> }
    core 37 { ids=<37> }
    core 38 { ids=<38> }
    core 39 { ids=<39> }
    core 40 { ids=<40> }
    core 41 { ids=<41> }
    core 42 { ids=<42> }
    core 43 { ids=<43> }
    core 44 { ids=<44> }
    core 45 { ids=<45> }
    core 46 { ids=<46> }
    core 47 { ids=<47> }
    core 48 { ids=<48> }
    core 49 { ids=<49> }
    core 50 { ids=<50> }
    core 51 { ids=<51> }
    core 52 { ids=<52> }
    core 53 { ids=<53> }
    core 54 { ids=<54> }
    core 55 { ids=<55> }
    core 56 { ids=<56> }
    core 57 { ids=<57> }
    core 58 { ids=<58> }
    core 59 { ids=<59> }
    core 60 { ids=<60> }
    core 61 { ids=<61> }
    core 62 { ids=<62> }
    core 63 { ids=<63> }
  }
}
CPU proc 1d0000000000000b: allocated <0>
CPU proc 1d00000000000011: allocated <32>
CPU proc 1d00000000000012: allocated <1>
CPU proc 1d00000000000005: allocated <33>
CPU proc 1d0000000000001f: allocated <2>
CPU proc 1d00000000000020: allocated <34>
CPU proc 1d00000000000009: allocated <3>
CPU proc 1d0000000000000a: allocated <35>
CPU proc 1d00000000000001: allocated <4>
utility proc 1d00000000000000: allocated <16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63>
CPU proc 1d0000000000000e: allocated <36>
CPU proc 1d0000000000000f: allocated <5>
CPU proc 1d00000000000017: allocated <37>
CPU proc 1d00000000000018: allocated <6>
CPU proc 1d00000000000004: allocated <38>
CPU proc 1d00000000000013: allocated <7>
CPU proc 1d00000000000014: allocated <39>
CPU proc 1d0000000000001d: allocated <8>
CPU proc 1d0000000000001e: allocated <40>
CPU proc 1d00000000000015: allocated <9>
CPU proc 1d00000000000016: allocated <41>
CPU proc 1d00000000000010: allocated <10>
dedicated worker (generic) #1: allocated <16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63>
CPU proc 1d00000000000008: allocated <42>
dedicated worker (generic) #2: allocated <16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63>
CPU proc 1d0000000000001b: allocated <11>
CPU proc 1d0000000000001c: allocated <43>
CPU proc 1d00000000000019: allocated <12>
CPU proc 1d0000000000001a: allocated <44>
DMA request queue: allocated <16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63>
CPU proc 1d00000000000002: allocated <13>
CPU proc 1d0000000000000c: allocated <45>
CPU proc 1d0000000000000d: allocated <14>
CPU proc 1d00000000000006: allocated <46>
CPU proc 1d00000000000007: allocated <15>
CPU proc 1d00000000000003: allocated <47>
```

2. 1 process, 1 node with `srun` (still with `-ll:cpu 32`): 51 s

Realm output:

```
core map {
  domain 0 {
    core 0 { ids=<0> }
    core 1 { ids=<1> }
    core 2 { ids=<2> }
    core 3 { ids=<3> }
    core 4 { ids=<4> }
    core 5 { ids=<5> }
    core 6 { ids=<6> }
    core 7 { ids=<7> }
    core 8 { ids=<8> }
    core 9 { ids=<9> }
    core 10 { ids=<10> }
    core 11 { ids=<11> }
    core 12 { ids=<12> }
    core 13 { ids=<13> }
    core 14 { ids=<14> }
    core 15 { ids=<15> }
    core 16 { ids=<16> }
    core 17 { ids=<17> }
    core 18 { ids=<18> }
    core 19 { ids=<19> }
    core 20 { ids=<20> }
    core 21 { ids=<21> }
    core 22 { ids=<22> }
    core 23 { ids=<23> }
    core 24 { ids=<24> }
    core 25 { ids=<25> }
    core 26 { ids=<26> }
    core 27 { ids=<27> }
    core 28 { ids=<28> }
    core 29 { ids=<29> }
    core 30 { ids=<30> }
    core 31 { ids=<31> }
  }
  domain 1 {
    core 32 { ids=<32> }
    core 33 { ids=<33> }
  }
}
dedicated worker (generic) #2: allocated <30,31>
CPU proc 1d0000000000000a: allocated <0>
CPU proc 1d0000000000000b: allocated <32>
DMA request queue: allocated <30,31>
CPU proc 1d00000000000013: allocated <1>
CPU proc 1d00000000000014: allocated <33>
CPU proc 1d00000000000015: allocated <2>
CPU proc 1d00000000000016: allocated <3>
CPU proc 1d00000000000017: allocated <4>
CPU proc 1d00000000000018: allocated <5>
CPU proc 1d00000000000019: allocated <6>
CPU proc 1d0000000000001a: allocated <7>
CPU proc 1d0000000000001b: allocated <8>
CPU proc 1d0000000000001c: allocated <9>
CPU proc 1d0000000000001d: allocated <10>
CPU proc 1d0000000000001e: allocated <11>
CPU proc 1d0000000000001f: allocated <12>
CPU proc 1d00000000000020: allocated <13>
CPU proc 1d00000000000004: allocated <14>
CPU proc 1d00000000000002: allocated <15>
CPU proc 1d00000000000001: allocated <16>
dedicated worker (generic) #1: allocated <30,31>
CPU proc 1d0000000000000c: allocated <17>
CPU proc 1d0000000000000d: allocated <18>
CPU proc 1d0000000000000e: allocated <19>
CPU proc 1d0000000000000f: allocated <20>
CPU proc 1d00000000000010: allocated <21>
CPU proc 1d00000000000011: allocated <22>
CPU proc 1d00000000000012: allocated <23>
utility proc 1d00000000000000: allocated <30,31>
CPU proc 1d00000000000003: allocated <24>
CPU proc 1d00000000000009: allocated <25>
CPU proc 1d00000000000008: allocated <26>
CPU proc 1d00000000000007: allocated <27>
CPU proc 1d00000000000006: allocated <28>
CPU proc 1d00000000000005: allocated <29>
```

`srun` is acknowleging the `--cpu_bind verbose` but doesn't seem to want to print anything.

**Comment by rupanshusoi** [comment] 2020-07-10 11:23
> Can you confirm: "launching application directly" means using the same number of cores? I don't see any reason why that should be any different than running "1 process, 1 node" assuming the `-ll:cpu` value is the same... unless the core binding is off.

I don't think the 5 s difference is significant here. However, I did some more testing with a finer grid and got some interesting results which will hopefully be conclusive in figuring out where the problem is.

I wanted to replicate this difference (which I think is significant)

> 32 cores per process, 1 process, 1 node: 50 s
> 16 cores per process, 2 processes per node, 1 node: 1 min 44 s

I ran the following two commands

1. `srun -p compute -v -c 18 python3 regent.py solver.rg -ll:cpu 16 -lg:prof ...`  completed in 55 s

2. `srun -p compute -v -c 9 -n 2 python3 regent.py solver.rg -ll:cpu 8 -lg:prof ...` completed in 6 min 51 s

Legion Prof output for both is on [http://sapling.stanford.edu/~rupanshu/](url) in files prefixed `srun`.

**Comment by elliottslaughter** [comment] 2020-07-10 16:13
Can you try `srun -c 64`? You are clearly not getting all the cores in the `srun -c 34` job, and that could easily explain a performance difference.

Let's get this right first, and then we can revisit the issue with 1 vs 2 processes per node.

For what it's worth, I would always use `srun -c 64`, or `srun -c 32 -n 2`, even if the `-ll:cpu` value is smaller. We really want Legion to control the core assignment. You are only shooting yourself in the foot if you let srun give Legion a smaller number of cores than what is available on the whole machine.

**Comment by rupanshusoi** [comment] 2020-07-10 16:41
You're right, that brings down the time in the second case to 56 s. I think this solves a large chunk of the problem, but I'm still seeing slowdown when I increase the number of subregions of my main partition. For example, both runs above were for 16 subregions. If I increase the number to 60 and do `srun -c 32 -n 2 python3 regent.py solver.rg -ll:cpu 30` then it's back to poor performance.

If you look at the graph for the second run, you will notice that the utility processor looks overloaded. Can that be a possible reason?

**Comment by elliottslaughter** [comment] 2020-07-10 16:47
Can you post the link I'm supposed to be looking at? http://sapling.stanford.edu/~rupanshu/srun1 and http://sapling.stanford.edu/~rupanshu/srun2 both look like low utility utilization to me.

**Comment by rupanshusoi** [comment] 2020-07-10 16:57
I meant `srun2`. Maybe I'm mistaken, because the numbers don't go up than 20%, but I was talking about something like the tall stack of tasks you see here:

![Screenshot from 2020-07-10 22-21-56](https://user-images.githubusercontent.com/50739306/87179221-0171be00-c2fc-11ea-9d4a-31756ca98d1e.png)

I don't see anything resembling this in `srun1`. However, if you think this is normal, then we need to find out why increasing the number of subregions gives bad performance and sometimes the Realm warning

`[0 - 7f509683e780]  744.742274 {4}{spill}: current spill usage = 1073753840 bytes, peak = 1073753840`

**Comment by elliottslaughter** [comment] 2020-07-10 17:06
Ok, I guess a couple things:

1. You seem to be missing one of the nodes in this profile. Did you run with `-lg:prof 2`? The argument to that flag is the number of nodes to profile. You need all the nodes or else we can't see everything that's going on.

2. There are gaps in this profile where nothing seems to be going on. This could indicate that there is something going on with the other node, but we just can't see it because it's not being profiled.

3. Since were doing multi-node now, there are couple other standard questions I would ask:

    - Are you using `control_replication`? This will be important for scaling. Even on 2 nodes, I would start using it so that you're following best practices. I can talk more about what this means if you aren't using it yet.
    - Are you using tracing? Of the stuff I do see on the utility cores, it seems to be mostly doing physical dependence analysis, which would go away if we were using tracing.

**Comment by rupanshusoi** [comment] 2020-07-10 17:09
This run was 2 processes run on a single node, so I only used `-lg:prof 2`. No, I don't use control replication yet. And yes, I did use tracing in at least some parts of the code.

**Comment by elliottslaughter** [comment] 2020-07-10 17:12
Did you get two log files? Did you run them both through `legion_prof.py`?

We should talk about control replication. Though it probably will not fix your immediate issue, it is considered a best practice, and will be important for any sort of scaling.

**Comment by rupanshusoi** [comment] 2020-07-10 17:15
No, I think I only got one profile. If you want, I can redo this exact run (with `-c 9` etc) but force `srun` to use 2 nodes, 1 for each process. The time taken should be pretty close to what you see here. Would that be helpful?

**Comment by elliottslaughter** [comment] 2020-07-10 17:17
The number of physical nodes should not matter.

Can you show me the full command line? Maybe you're missing a `%` in the argument to `-lg:prof_logfile prof_%.gz`?

**Comment by rupanshusoi** [comment] 2020-07-10 17:18
Let me run it again and see.

**Comment by rupanshusoi** [comment] 2020-07-10 17:25
I just started the run with `srun -v -p compute -c 9 -n 2 python3 ~/legion/language/regent.py meshfree_solver.rg -fcuda 0 -ll:cpu 8 -ll:csize 10000 -lg:prof 1 -lg:prof_logfile prof_%.gz` and I only see `prof_0.gz` created. I'm assuming all such files are created at the start of the run?

**Comment by elliottslaughter** [comment] 2020-07-10 17:27
Can you add `-level announce=2` and show me what you get?

**Comment by elliottslaughter** [comment] 2020-07-10 17:28
Oh, well you have `-lg:prof 1` on that command line. You need `-lg:prof 2` or you won't get a profile for the second node.

**Comment by rupanshusoi** [comment] 2020-07-10 17:50
Please see [http://sapling.stanford.edu/~rupanshu/srun2-2](url)

**Comment by rupanshusoi** [comment] 2020-07-10 17:53
For some reason the link doesn't seem to be working from GitHub, but you should be able to see `srun2-2` in the same place.

**Comment by elliottslaughter** [comment] 2020-07-10 17:57
I think I fixed your link.

I see the utility processor is doing a lot of waiting. It's not "full" in the sense of being CPU bound, but it may be causing the gaps.

I think you are not actually using tracing. You can clearly see boxes labeled "physical dependence analysis" on the utility process, and those should not exist if tracing is enabled.

If you have the default mapper, you need the flag `-dm:memoize`. If you have a custom mapper (that does not inherit from the default mapper) then there's a method you need to customize.

**Comment by rupanshusoi** [comment] 2020-07-10 18:18
I'm trying to generate the profiles with `-dm:memoize` but it seems to have gotten even slower? This run usually takes 7 mins but right now it has been over 15 and it's still running. I am using the default mapper, by the way.

**Comment by rupanshusoi** [comment] 2020-07-10 18:25
Ok if I run with one process I get this warning so probably my code isn't suitable for tracing

`[0 - 7fab102b8780]   44.848391 {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is highly likely that trace 1 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: blocking call. Please change the mapper to stop making memoization requests. (from file /storage/home/anil/legion/runtime/legion/legion_trace.cc:1830)`

**Comment by elliottslaughter** [comment] 2020-07-10 18:33
Right, so this says that tracing is not actually working. There are some steps we can go through to debug this, but some preliminary questions:

  1. Do you launch the same set of tasks every time through the trace?
  2. Do you do anything like create new regions or partitions inside the trace?
  3. Do you wait on any futures inside the trace?

**Comment by rupanshusoi** [comment] 2020-07-10 18:42
1. Yes
2. No
3. Yes, I had a `printf` that depended on a task's result. I commented it out, and now the warning gives `virtual mapping` as the reason instead of `blocking call`. 

Question: Where should I use `__demand(__trace)`? I have it on my main loop, but also on the task launches inside it. So something like

```
__demand(__trace)
for i = 0, n do
  __demand(__index_lauch, __trace)
  for color in p.colors do
    foo(p[color])
  end
end
```

**Comment by elliottslaughter** [comment] 2020-07-10 18:45
You only need the `__trace` on the outer loop.

Are any of the tasks called inside the trace leaf tasks? (You can check by marking then with `__demand(__leaf)` and seeing if it fails or not.)

**Comment by rupanshusoi** [comment] 2020-07-10 18:54
Yes, a few of them are indeed leaf tasks. But they are all called inside index launches -- imagine `foo` to be a leaf task in my last example. I put `__demand(__leaf)` on some task declarations and it did not fail.

**Comment by elliottslaughter** [comment] 2020-07-10 19:01
I'm asking if 100% of the tasks called inside the trace are leaf tasks. Your error about virtual mappings indicates that there is probably at least one that is not. That's the one we're looking for, since we do not support tracing non-leaf tasks at this time.

The index launch is fine. Keep that as is.

**Comment by rupanshusoi** [comment] 2020-07-10 19:06
Oh, I thought you meant we do not want leaf tasks. I have refactored the code and it ran without any warnings, at least when I used one process. Let me try out using two processes and see if the initial gap reduced.

**Comment by rupanshusoi** [comment] 2020-07-10 19:32
For some reason, 
`srun -v -p compute -c 9 -n 2 python3 ~/legion/language/regent.py meshfree_solver.rg -fcuda 0 -ll:cpu 8 -ll:csize 10000 -dm:memoize -lg:prof 2 ...` 
decided to segfault after 15+ minutes, but
`srun -v -p compute -c 9 -n 2 python3 ~/legion/language/regent.py meshfree_solver.rg -fcuda 0 -ll:cpu 16 -ll:csize 10000 -dm:memoize -lg:prof 2 ...`
ran in 100 s. (Note the `-c` and `-ll:cpu` values) Profile for this run is up.

**Comment by elliottslaughter** [comment] 2020-07-10 19:53
Have you ever run with `-fbounds-checks 1`? That might be a good idea, just to be sure that source of bugs is not present.

Where is the profile? Is it this one? http://sapling.stanford.edu/~rupanshu/srun2-2-mem/

The most obvious thing about that profile is that the tasks are not being assigned to the other node at all. Are there enough subregions to fill the machine in this run?

**Comment by rupanshusoi** [comment] 2020-07-10 19:57
Yes, I've successfully run with `-fbounds-checks 1`. And yes, that's the profile.

I think even though I used `-n 2` this is somehow being treated as a single process run (probably because of the weird choice of `-c 9` and `-ll:cpu 16`), hence the empty node 1 in the profile. The problem now seems to be that enabling tracing for 2 processes seems to degrade performance and segfault.

**Comment by elliottslaughter** [comment] 2020-07-10 20:01
It may be that remote tracing is not a performance win. I think the only way to fix this is control replication. The basic steps for this would be:

1. Switch to `control_replication` branch
2. Add `__demand(__replicable)` to your top-level task
3. (Optional, but important for performance): write a custom sharding functor
4. Run with the flag `-dm:same_address_space 1`

But for initial testing you can get away with only doing (1), (2) and (4).

**Comment by rupanshusoi** [comment] 2020-07-10 20:09
Ok, I will get to this in the morning. Just for my own sanity, how likely do you think that this is an installation/configuration problem instead (GASNet, MPI, Slurm)? MPI and Slurm work fine for the other codes we run on this machine though. Since we're seeing such stark performance differences between going from one process to two, my impression was that MPI (or maybe GASNet) was not handling inter-process communication properly.

**Comment by elliottslaughter** [comment] 2020-07-10 22:41
A couple things:

  * You can verify the MPI/Slurm configuration yourself by checking hostnames and `-ll:show_rsrv`. So there's really no way to mess that up (that you wouldn't notice).
  * GASNet is actually not that sensitive to configuration, in my experience, but you can certainly check. By far the highest order bit though is what conduit you are using, and if you've got the correct one usually that's all you care about.
  * At any rate, I've never seen copies be an issue in any of your profiles. (Particularly if you go look at the gaps, you will not see copies take up that part of the timeline.)
  * The things I did see in the timeline were mapping issues (not using the second node's cores at all), and utility processor overhead (waiting on remote messages, almost certainly a symptom of not using DCR).

So I'd say I'm pretty confident DCR will help those last issues. Which is not to say that you can't have real issues with network performance, but those are more likely to appear as you scale out (or perhaps if the regions in the application are especially sparse).

**Comment by rupanshusoi** [comment] 2020-07-11 14:50
@elliottslaughter I have some more interesting profiles for you to look at.

So I went ahead and implemented DCR in my solver. While it did reduce the running time, the central problem is far from being solved. Consider the following two runs, which only differ in the value of `-c` given to `srun`.

1. Run A: `srun -c 9 -n 2 python3 regent.py solver.rg -ll:cpu 8 -dm:same_address_space 1` : Took about five and a half minutes. I used `__demand(__replicable)` on my `main` task (the one called from `regentlib.start`). This is the same command from yesterday, and it was taking 6 min 50 s earlier, so CR definitely helped. Profile for this is http://sapling.stanford.edu/~rupanshu/srun2-2-CR/

2. Run B: `srun -c 32 -n 2 python3 regent.py solver.rg -ll:cpu 8`: Took < 1 min, even without CR. Profile is here http://sapling.stanford.edu/~rupanshu/srun-32-procs-per-process/

A few observations:

1. CPUs on node 1 don't seem to be used very much in both runs. By far the heaviest task my solver has is `cal_flux_residual` (shown in cyan in both profiles), and it runs exclusively on node 0 in both cases. In spite of this, the (average) time gap between consecutive executions of `cal_flux_residual` on the same core in run B < 1 ms, while the same measurement for run A > 1 s.

2. The utility processor seems much less burdened in run B than run A. 

3. Judging from CPU usage, the main time loop of the solver (where `cal_flux_residual` lives) seems to start at around 207 s in run A, and 7.5 s in run B.

This gives me the impression that the problem is not with how the solver is written. If the issue was with Regent/Legion not being able to extract enough parallelism, then we would not see such a stark constrast between these two runs, because both effectively use identical computing power. 

What do you think?

**Comment by rupanshusoi** [comment] 2020-07-11 16:16
I've also profiled a run on Sapling here http://sapling.stanford.edu/~rupanshu/sapling/

All CPUs seem to be used equally here. I ran with `mpirun -n 2 -H n0003,n0002 --bind-to none regent.py solver.rg -ll:cpu 8 -lg:prof 2 ...`

**Comment by elliottslaughter** [comment] 2020-07-13 18:39
One thing to realize here is that Legion has more than one "extra" thread: there are utility threads, DMA threads, active message threads, possibly threads for the network, etc. When you run `srun -c 9 ... -ll:cpu 8` you are basically shoving all those extra threads onto a single core. Probably what's going on is that those threads are fighting for CPU time (because some of those threads intentionally spin to minimize latency).

Going forward, I would *always* use `srun -c 32` (or whatever the maximum number of cores is). As you can see, it clearly has a huge benefit, and it comes at no downside.

Can you please describe the steps you did to enable DCR? I see you used `__demand(__replicable)`, but what branch of Legion were you on? The runs here look like they weren't actually using DCR.

**Comment by rupanshusoi** [comment] 2020-07-13 18:46
> But for initial testing you can get away with only doing (1), (2) and (4).

I did these 3 steps. Possibly the way my application is written is making it hard for the runtime to use DCR? If there are any guidelines for this, please let me know.

**Comment by elliottslaughter** [comment] 2020-07-13 18:51
Ok, I guess one other things to sanity check:

1. Are you using index launches in the top-level task (you can check with `__demand(__index_launch)`)?

If this is true, then we may be at the point were it would help for me to run the code directly, but we can discuss that offline.

**Comment by rupanshusoi** [comment] 2020-07-13 18:54
Yes, I've tried to use them wherever the compiler allowed.

**Comment by elliottslaughter** [comment] 2020-07-13 19:01
If you have index launches and are successfully running with DCR and the default projection functor, there really should be at least *some* tasks running on the other node. I guess at this point, we should take this offline to discuss having me run the code directly (if possible).

**Comment by rupanshusoi** [comment] 2020-07-13 19:27
Sure, I've sent you an invite here on GitHub.

**Comment by elliottslaughter** [comment] 2021-06-15 22:14
@rupanshusoi Looks like we discussed a bunch of different things in this issue. Are any of them still relevant? If not we might close this issue.

**Comment by rupanshusoi** [comment] 2021-06-15 22:34
All these issues were resolved in the time leading up to the PAW submission. Thanks!

**Closed** 2021-06-15 22:55 UTC
Labels: Regent, backlog, bug
