### ISSUE TITLE
Regent: Error in struct handling

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#535] opened 2019-05-06 22:12 UTC
Based on a reproducer by @mariodirenzo.

Unzip [testConfig.tar.gz](https://github.com/StanfordLegion/legion/files/3150014/testConfig.tar.gz) and run:

```
make
./testConfig.sh
```

These two statements should both print `4.200000e+01`, but the second prints `0.000000e+00`:

```
   C.printf("%e\n", config[0].BC.xBCLeftInflowProfile.u.Constant.velocity[0])
   var c = config[0]
   C.printf("%e\n", c.BC.xBCLeftInflowProfile.u.Constant.velocity[0])
```

**Comment by elliottslaughter** [comment] 2019-05-07 23:24
```ifndef PROMETEO_DIR
  $(error PROMETEO_DIR is not set)
endif
```

What's PROMETEO?

**Comment by manopapad** [comment] 2019-05-07 23:56
Prometeo is the name of the original application that this reproducer comes from. Please set `PROMETEO_DIR` to the directory where you extracted the reproducer.

**Comment by mariodirenzo** [comment] 2019-05-13 20:37
Is there any update about this issue?

**Comment by magnatelee** [comment] 2019-05-13 21:33
I think the bug is actually in Terra. I wrote a terra function with the same lines of code and observed the same buggy behavior. When I changed the code to use a Terra struct isomorphic to the imported C struct, the bug disappeared. I suspect that Terra doesn't correctly emit copy assignments for imported structs. 

@mariodirenzo I believe You can work around this issue with the new address-of operator that Elliott added a couple of days ago, which can replace the array-of-size-1 hack in your code. You just need to create a variable of the `Config` type and and pass its address to the C function, just like you would do in C.

**Comment by mariodirenzo** [comment] 2019-05-14 01:03
@magnatelee thanks for replying. Can you port this feature on the ``parallelizer-dcr`` branch?

**Comment by magnatelee** [comment] 2019-05-14 09:07
I just updated the `parallelizer-dcr` branch with those changes. (You will need to hard reset your local branch as I rebased it.)

**Comment by elliottslaughter** [comment] 2019-05-14 18:18
@magnatelee Can you please submit a Terra bug so we don't lose track of this?

**Comment by mariodirenzo** [comment] 2019-05-15 17:16
Hi all, the workaround proposed by @magnatelee does not solve the problem if I pass the struct to a task like this :
```
task out(config : Config)
   C.printf("%e\t%e\t%e\n", config.BC.xBCLeftInflowProfile.u.Constant.velocity[0],
                            config.BC.xBCLeftInflowProfile.u.Constant.velocity[1],
                            config.BC.xBCLeftInflowProfile.u.Constant.velocity[2])
end
```

The struct config is used in the solver to provide input data to almost every task and, as far as I know, I cannot pass it by reference to tasks that are not inlined, right?

**Comment by mariodirenzo** [comment] 2019-06-02 01:59
is there any update regarding this issue?

**Comment by elliottslaughter** [comment] 2019-06-03 18:35
Can someone (@magnatelee or someone else) post a complete, self-contained reproducer? This looks like something that should just be a 10 line program.

**Comment by magnatelee** [comment] 2019-06-04 06:15
I submitted a Terra bug: https://github.com/zdevito/terra/issues/372

**Comment by elliottslaughter** [comment] 2019-06-27 15:47
This has been fixed in Terra, and I have updated the `luajit2.1` branch to include the fix. @manopapad or @mariodirenzo to confirm.

**Comment by elliottslaughter** [comment] 2019-06-27 17:00
Never mind, turns out the original bug isn't fixed in the case where the type declarations are coming from a C header file.

**Comment by elliottslaughter** [comment] 2019-07-19 20:59
@manopapad @mariodirenzo Can you please try again? Should hopefully be fixed for real this time.

**Comment by elliottslaughter** [comment] 2019-08-20 17:53
This reproducer is still failing, even with the latest fix, so clearly we're still missing something: https://gist.github.com/elliottslaughter/cd1340789e399e022010fa08da46bd98

**Comment by magnatelee** [comment] 2019-08-20 18:22
Just to keep track of the status, this test, though it passes, takes tens of minutes without the hack in f71263fb: https://gist.github.com/magnatelee/5bc6d0bb51a65440e7647efbfa2a9e5b
And the slowdown was caused by the attempted fix of this issue, which by the way hasn't yet solved it completely.

**Comment by elliottslaughter** [comment] 2019-08-22 20:10
Ok, @magnatelee's reproducer is now compiling efficiently with Legion at 18f9091 (i.e. before the hacks) and with https://github.com/zdevito/terra/pull/390. This is still the remaining issue with `bug372d.t` which is still causing my reproducer from two comments ago to fail.

**Comment by elliottslaughter** [comment] 2019-08-23 22:55
All of the outstanding reproducers are now fixed, so please test this again with your larger codes.

**Comment by elliottslaughter** [comment] 2019-08-23 23:41
Sounds like @mariodirenzo has confirmed this is fixed, but let me know if you run into any more issues along these lines.

**Closed by elliottslaughter** 2019-08-23 23:41 UTC
Labels: Regent
