### ISSUE TITLE
Non deterministic behavior on 3d regions partitioned along y or z

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#653] opened 2019-10-09 18:35 UTC
I am currently experiencing a non-deterministic behavior of my solver (written in Regent) that leads it to produce a NaN at a random iteration even though the setup and the algorithm of the solver should be deterministic.
This weird behavior shows up only if the 3d region, on which the solver operates, is partitioned along the y and z direction. Everything seems to work fine if the partitioning is performed only in the x-direction.
I have been able to reproduce the error only on 16 nodes with 4 GPUs per node.
I do not know if the issue reproduces also downscaling the problem size.
I am using the version of Legion/Regent at `a5325052` of the `parallelizer-dcr` branch

**Comment by lightsighter** [comment] 2019-10-10 06:33
@mariodirenzo I found and fixed the possibly related bug that I was chasing. I've pushed fixes to the master and control replication branches. Can you rebase the changes into parallelizer-dcr and then see if your issue still reproduces?

**Comment by mariodirenzo** [comment] 2019-10-10 14:53
ok, I'll test it ASAP.
Thanks

**Comment by mariodirenzo** [comment] 2019-10-13 22:11
It does not look like the issue is solved and the execution seems much slower when the partitioning is applied along y and z.

**Comment by lightsighter** [comment] 2019-10-13 23:12
> the execution seems much slower when the partitioning is applied along y and z
How long did you run it for? The change I made should only have impacted start-up and even then very minimally. Were there many other changes from when you did the rebase or just a few?

This is the new parallelizer right? Can we try to get a Legion Spy trace of a failed run? Can we also try a run after building with -DDISABLE_VIEW_REPLICATION in CC_FLAGS?

**Comment by mariodirenzo** [comment] 2019-10-14 01:16
> How long did you run it for? 
19 iterations (paritioning only in x, the solver makes almost 200 iterations in the same amount of time)

> Were there many other changes from when you did the rebase or just a few?
The base of the version that I was using before is 019f0f89

> This is the new parallelizer right?
right

> Can we try to get a Legion Spy trace of a failed run?
I'll try to make them tomorrow but the logs are going to be quite long

> Can we also try a run after building with -DDISABLE_VIEW_REPLICATION in CC_FLAGS?
I'll try it tomorrow

**Comment by lightsighter** [comment] 2019-10-14 01:50
> 19 iterations (paritioning only in x, the solver makes almost 200 iterations in the same amount of time)
Ah, this part makes sense to me. The cost of partitioning in the other dimensions will definitely go up until we can turn on tracing with control replication, but let's not worry about that for now.

> I'll try to make them tomorrow but the logs are going to be quite long
Maybe only capture 3 iterations for the Legion Spy logs. The thing I fixed earlier would occur during the first iteration.

> I'll try it tomorrow
Yes, let's do this one first. It would also have fixed the bug you found the last time too and it is easy to test.

**Comment by mariodirenzo** [comment] 2019-10-14 04:10
> 19 iterations (partitioning only in x, the solver makes almost 200 iterations in the same amount of time)
>> Ah, this part makes sense to me. The cost of partitioning in the other dimensions will definitely go up until we can turn on tracing with control replication, but let's not worry about that for now.

But, I do not see such a large slowdown with the older version of Legion

**Comment by lightsighter** [comment] 2019-10-14 06:06
> But, I do not see such a large slowdown with the older version of Legion

What is the "older" version of Legion? Do you have a commit hash for that?

**Comment by mariodirenzo** [comment] 2019-10-14 06:13
By older version I mean `parallelizer-dcr` based on 019f0f8.
The version that is slower is the one in `parallelizer-dcr-new`

**Comment by mariodirenzo** [comment] 2019-10-15 17:33
`-DDISABLE_VIEW_REPLICATION` seems to solve both the slow down of the solver and the NaN (the run performed 400 iterations without a problem in contrast with the 19-25 iterations of the standard build of Legion).
Do you need the legion spy logs of the run? In case, with or without `-DDISABLE_VIEW_REPLICATION`?

**Comment by lightsighter** [comment] 2019-10-16 02:12
I've disabled view replication for now and am moving in a direction where it will be permanently off in the near future unless we have a compelling use case to turn it back on. We'll leave this issue open for now to see if anyone complains about the performance of it being turned off.

**Comment by lightsighter** [comment] 2019-11-15 06:39
It is possible that this issue was actually fixed by commit ddc4b70b86, but I'm inclined to still leave view replication off because of the performance gains we've seen from turning it off. I'm also not totally confident that this commit fixes the issue, but it definitely is related.

**Comment by lightsighter** [comment] 2019-12-28 21:52
I believe that we've fixed the underlying cause for this issue and we haven't seen any performance regressions as a result of the fix. Closing this issue for the milestone.

**Closed by lightsighter** 2019-12-28 21:52 UTC
Labels: Legion, bug
