### ISSUE TITLE
Regent: uninitialized data warning

### ISSUE THREAD

**Issue by rupanshusoi** [StanfordLegion/legion#719] opened 2020-01-14 09:04 UTC
This warning comes up everytime I access some element from a region for the first time. For example, the following code snippet
```c
import "regent"
task main()
        var arr = region(ispace(int1d, 1), int)
        arr[0] = 2
end
regentlib.start(main)
```
outputs
```
[0 - 7fbe381b9700] {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 0 of operation Mapping (UID 3) in parent task main (UID 1) is using uninitialized data for field(s) 101 of logical region (1,1,1) (from file /home/rootpi/code/legion/runtime/legion/legion_ops.cc:539)[warning 1071] 
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
```
This has made it very difficult to access large regions. Also seems closely related to #671 
As far as I remember, this did not occur for an older version of regent. Even code from the official regent tutorial on physical regions gives this warning now.
I'm a beginner at regent, so any guidance or a workaround is really appreciated.

**Comment by lightsighter** [comment] 2020-01-14 09:17
This is a duplicate of #671 and stems from Regent not providing support for write-discard privileges which should be used anytime you write to a region for the first time. Right now you just have read-write privileges in the Regent language and the runtime is warning you to tell you that if you try to read a region that has never been written before then you are going to see uninitialized data. If there are lots of warnings you don't want to see you can disable them for now by passing the `-level runtime=5` flag on the command line.

**Comment by elliottslaughter** [comment] 2020-01-14 16:31
If you weren't accessing the region directly in this task, you could use `fill(r, 0)` to clear the region before accessing it. The reason why #671 is relevant is because if you *do* access the region in the same task, Regent will map it to an instance by default and that mapping will use RW.

**Comment by rupanshusoi** [comment] 2020-01-14 16:42
I'm having another problem with accessing regions, but I'm not sure if I should create another issue, so I'm just going to post it here. Any help will be really appreciated.
This code
```c
import "regent"

struct s
{
        arr : region(ispace(int1d, 1), int);
}

task main()
        var b : s
        b.arr[0] = 2
        regentlib.c.printf("%d\n", b.arr[0])
end
regentlib.start(main)
```
outputs
```
invalid privilege writes($5) for dereference of int1d(int32, $5)
b.arr[0] = 2
```
Even if I pass it to a task with explicit read-write permission
```c
import "regent"

struct s
{
        arr : region(ispace(int1d, 1), int);
}

task t(r: region(ispace(int1d), int))
where reads writes(r) do
        regentlib.c.printf("%d\n", r[0])
end

task main()
        var b : s
        t(b.arr)
end
regentlib.start(main)
```
I still get
```
invalid privileges in argument 1: reads($b.arr)
t(b.arr)
```
These errors vanish if I pass directly a region to t; the following
```c
task t(r: region(ispace(int1d), int))
where reads writes(r) do
        regentlib.c.printf("%d\n", r[0])
end

task main()
        var r = region(ispace(int1d, 1), int)
        r[0] = 2
        t(r)
end
````
outputs
```
2
```

**Comment by elliottslaughter** [comment] 2020-01-14 16:50
Regions in structs are a bit odd. If you create a region `A` of structs, and the struct contains a region `B`, then passing privileges on `A` doesn't get you privileges on `B`. We've thought about extensions to improve this, but they're not currently implemented.

But what are you trying to do? If we knew the overall goal we could help guide you in the right direction.

**Comment by rupanshusoi** [comment] 2020-01-14 17:39
I have a data structure "Point" implemented as a struct with various fields. I require an array of ints (or doubles) for some of the fields, and only the max size of the array is known at compile time. I thought of using ``` region(ispace(int1d, MAX_SIZE), int) ``` instead of simply ```int[MAX_SIZE]``` since I was able to initialise the struct by passing a region with a different size than ```MAX_SIZE```, but not by passing an array with a different size. 
Long story short, all I need is a nice way to have arrays (preferably of variable length, but if I'm not mistaken they aren't supported in regent) as members of a struct.

**Comment by elliottslaughter** [comment] 2020-01-14 20:13
If it's possible to use a fixed size array, that's the easiest approach right now. (You will necessarily waste some space; whether that's viable will depend on your application.)

There is a plan to add custom serializers to Regent, which would enable true variable size arrays. It's not currently high priority, but we could try to bump it up if you had a usecase for it that's not satisfied by allocating a static array with maximum size. I created this issue to track progress on it: #720

**Comment by elliottslaughter** [comment] 2020-01-16 00:37
I created https://github.com/StanfordLegion/legion/issues/721 to track progress on discard, though the particular case that caused the warning above should be fixed.

@rupanshusoi If that's all for now, I'm going to close this issue in favor of the other two. But please feel free to open new issues if you run into anything else.

**Closed by elliottslaughter** 2020-01-16 00:37 UTC
Labels: Regent

**Comment by rupanshusoi** [comment] 2020-01-16 02:16
Yup, thank you @elliottslaughter.
