### ISSUE TITLE
Regent: Slow atomic updates in CUDA tasks with LLVM 9

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#983] opened 2020-12-12 00:08 UTC
I found today that LLVM 9 (and likely other versions using the NVPTX backend) does not lower NVVM's atomic intrinsics, which makes the Regent compiler emit an ill-formed PTX. As a workaround, I changes the compiler to emit the slow atomic update implementation ([bab441ea](https://gitlab.com/StanfordLegion/legion/-/commit/bab441eaf709b545a2f3de93676fae74d75bef10)), but we need to teach the compiler how to emit fast atomic updates using the NVPTX backend.

**Comment by elliottslaughter** [comment] 2021-01-19 21:55
We believe this is because newer LLVM versions seem to have switched to using dedicated instructions rather than intrinsics for atomic support. If we had support for the right instructions in Terra we ought to be able to code generate this.

**Comment by elliottslaughter** [comment] 2022-04-02 05:15
This has been added in https://gitlab.com/StanfordLegion/legion/-/merge_requests/459 but does not fully address #1041 in my initial testing.

**Comment by elliottslaughter** [comment] 2022-04-04 19:02
I went ahead and merged this because it seems to be doing its job. The remaining regressions seem to be coming from other places, so while they still need to be addressed, it won't be through the atomics.

**Closed by elliottslaughter** 2022-04-04 19:02 UTC
Labels: Regent, best effort
