### ISSUE TITLE
Regent: CUDA errors are not checked during kernel launches

### ISSUE THREAD

**Issue by sparkasaurusRex** [StanfordLegion/legion#713] opened 2019-12-19 22:20 UTC
@magnatelee and I are suspicious that Regent is not checking CUDA errors. In one test case, running Regent tasks on the CPU is fine while running them on a GPU gives an output of all zeros.

**Comment by magnatelee** [comment] 2019-12-19 22:26
Just to clarify, this happens only when the CUDA hijack in Realm is turned off. Realm catches any CUDA errors when the hijack is used.

**Comment by magnatelee** [comment] 2020-02-05 21:52
The root cause of this issue was the Regent compiler not following the right procedure to register a CUDA binary via the default CUDA runtime and only being able to interact with the Realm hijack. I'll open a new issue and close this one, as a temporary fix is in place in the hijack_registration_hack.

**Closed by magnatelee** 2020-02-05 21:52 UTC
