### ISSUE TITLE
Regent: Running regent code with GPU support enabled gives undefined symbol error

### ISSUE THREAD

**Issue by Nischay-Pro** [StanfordLegion/legion#752] opened 2020-02-24 09:24 UTC
Hi,

I compiled Regent with LLVM 6.0.1 and CUDA 10.2.89 on my Centos 8 node.

On trying to run regent code with `-ll:gpu` I get the following error.

`
/opt/legion/language/terra/release/bin/terra: symbol lookup error: /opt/legion/bindings/regent/libregent.so: undefined symbol: _ZN6Legion8Internal36register_builtin_gpu_reduction_tasksERKNSt3__13setIN5Realm9ProcessorENS1_4lessIS4_EENS1_9allocatorIS4_EEEERNS2_INS0_7RtEventENS5_ISC_EENS7_ISC_EEEE
`

Any help will be appreciated.

**Comment by streichler** [comment] 2020-02-24 14:08
Which branch/commit of the Legion tree are you using?
How are you building Regent?  (i.e. What is your command line?  There are potential failure modes we can explore for both the make and cmake versions of the build, but they'll be different.)

**Comment by Nischay-Pro** [comment] 2020-02-24 18:34
I'm on the master branch with the latest commit pulled.

I'm using the gnu toolchain provided by CentOS to build LLVM 6.0.1 through spack.

I've also installed cuda 10.2.89 through spack. Before running the installation script I load the llvm and cuda modules via spack. 

For the command line instruction I run its 

`python3 ./install.py --cuda`

**Comment by lightsighter** [comment] 2020-02-25 07:55
This is effectively a duplicate of issue #735. Use the make build system instead of cmake to work around it until @streichler and @elliottslaughter add support for that issue in the cmake build.

**Comment by Nischay-Pro** [comment] 2020-02-25 08:25
Ok. So I tried building Regent with the following flags `--cuda --no-cmake --no-terra-cmake` and I have a new issue while compiling Terra. I get the follow error

```
< build/llvm_objects/llvm_list build/bin/luajit-2.0.5 src/unpacklibraries.lua build/llvm_objects
build/bin/luajit-2.0.5: src/unpacklibraries.lua:20: attempt to index local 'archivepath' (a nil value)
stack traceback:
	src/unpacklibraries.lua:20: in main chunk
	[C]: at 0x00404720
make: *** [Makefile:221: build/llvm_objects/llvm_list] Error 1
Traceback (most recent call last):
  File "./install.py", line 471, in <module>
    driver()
  File "./install.py", line 468, in driver
    install(**vars(args))
  File "./install.py", line 361, in install
    external_terra_dir, thread_count, llvm)
  File "./install.py", line 190, in install_terra
    build_terra(terra_dir, terra_branch, use_cmake, cmake_exe, thread_count, llvm)
  File "./install.py", line 144, in build_terra
    cwd=terra_dir)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'all', '-j', '80']' returned non-zero exit status 2.
```

**Comment by lightsighter** [comment] 2020-02-25 09:00
You might ned to blow-away your terra instance when switching build systems (not something we usually encourage users to do). I would just delete the `terra` directory and let the build system check it out and built it from scratch.

**Comment by Nischay-Pro** [comment] 2020-02-25 09:39
Same error persists. I tried deleting the directory `terra`. I've also tried resetting my legion folder with `git clean -fxd`.

**Comment by lightsighter** [comment] 2020-02-25 10:59
Ok, I'll let @elliottslaughter comment.

**Comment by elliottslaughter** [comment] 2020-02-25 17:02
Get rid of `--no-terra-cmake`, delete `terra`, and try again. CMake is the recommended build system for Terra.

**Comment by Nischay-Pro** [comment] 2020-02-26 14:39
Thanks @elliottslaughter . I was able to successfully compile and execute the code. While my results did not diverge I am getting the following warning message.

```
warning: Linking two modules of different data layouts: '/opt/spack/opt/spack/linux-centos8-broadwell/gcc-9.2.0/cuda-10.2.89-iakvf5n76m2mlemijqhdaow5w4v5iibe/nvvm/libdevice/libdevice.10.bc' is '' whereas 'external' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'
```

I'm assuming it's safe to ignore this warning?

**Comment by elliottslaughter** [comment] 2020-02-26 18:43
Yes, that warning should be fine to ignore.

**Comment by elliottslaughter** [comment] 2020-02-26 18:53
Closing since the remaining unresolved parts of this issue correspond exactly to #735. But please feel free to let us know if there anything else (either here or in a new issue).

**Comment by rupanshusoi** [comment] 2020-02-28 12:39
Even though we ran with `-fcuda 1`, legion prof isn't displaying any GPU profile. Checking `nvidia-smi` during execution confirmed that the GPU was being used.

**Comment by seemamirch** [comment] 2020-02-28 17:58
Can you upload the prof files (produced when you the application)?

On Feb 28, 2020, at 4:39 AM, Rupanshu Soi <notifications@github.com<mailto:notifications@github.com>> wrote:


Even though we ran with -fcuda 1, legion prof isn't displaying any GPU profile. Checking nvidia-smi during execution confirmed that the GPU was being used.

**Comment by rupanshusoi** [comment] 2020-02-28 21:28
You can find the .gz file here https://filebin.net/w3glnkq8o1p6pe16

**Comment by elliottslaughter** [comment] 2020-02-28 22:55
Did you also pass `-ll:gpu 1`?

**Comment by rupanshusoi** [comment] 2020-02-29 04:01
Yes.

**Comment by elliottslaughter** [comment] 2020-03-02 21:05
One more sanity check: are you using `__demand(__cuda)` on the tasks you want to run on the GPU?

**Comment by rupanshusoi** [comment] 2020-03-02 22:15
Yes, I'm using it on several tasks.

**Comment by elliottslaughter** [comment] 2020-03-02 22:34
I'm out of ideas at this point. @magnatelee what would we need to do to verify that the GPU tasks are being generated?

**Comment by streichler** [comment] 2020-03-02 23:03
Doing a run with `-level taskreg=2` will show which tasks are registered with which processors at the Realm level.

**Comment by rupanshusoi** [comment] 2020-03-09 17:43
My bad, I was using the `cuda` annotation where the task was being called, instead of putting it before the task definition. There is no problem, and you can go ahead and close this issue. Thanks.

**Comment by elliottslaughter** [comment] 2020-03-09 17:49
@rupanshusoi Can you share a code sample from before the fix? The compiler should throw an error if you put `__demand(__cuda)` where it isn't allowed.

Thanks.

**Comment by rupanshusoi** [comment] 2020-03-09 19:37
I was able to find a smaller reproducer. The following
```
import "regent"

task foo()
	var arr : int[2000]
	for i = 0, 2000 do
		arr[i] = 1
	end
end

task main()
	var arr = region(ispace(int1d, 2), int)
	fill(arr, 0)

	__demand(__cuda)
	for i in arr do
		foo()
	end
end
regentlib.start(main)
```
executes without errors but the GPU is not profiled in legion prof. If the for loop in `main` is changed to a for-num loop, the compiler correctly says that the CUDA annotation can't be used here. If we move the annotation to the top of the declaration of `foo()`, the profiling works as expected. The contents of `foo()` are irrelevant.

**Comment by elliottslaughter** [comment] 2020-03-09 19:51
Ok, in master as of 54b6974693b0c4878a2d60322ce202bfff85bbfb, this should be an error. I'm not sure why it wasn't before, but it will be going forward.

**Comment by elliottslaughter** [comment] 2020-03-09 22:21
Had to revert my change since it turns out `__forbid(__cuda)` is there for a reason. The correct fix (which I have yet to implement) is to reject it only when not inside a task that also has `__demand(__cuda)`.

**Comment by elliottslaughter** [comment] 2020-03-10 20:28
Ok, trying again with 2d7d9a253830ee79c980e541cfe6ba8ff148912b. Will close if it passes CI.

**Closed** 2020-03-10 21:46 UTC
Labels: Regent, bug, planned
