### ISSUE TITLE
internal assert in VersionManager::sanity_check line 6066

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#256] opened 2017-05-20 03:20 UTC
To reproduce this check out branch visualization 
cd legion/examples/visualization
git reset --hard 9eb265a5638842b594a2ec0c0918d9a3cd8d493f
make
./protoype1

you should see this output:
Alans-MacBook-Pro:visualization alanheirich$ ./prototype1 
[0 - 7fffb46e03c0] {4}{numa}: numa support not available in system
[0 - 7fffb46e03c0] {4}{threads}: reservation ('DMA threads') cannot be satisfied
[0 - 70000350c000] {4}{runtime}: Region requirements 0 and 1 of index task compositeTask (UID 4) in parent task topLevelTask (UID 1) are potentially interfering.  It's possible that this is a false positive if there are projection region requirements and each of the point tasks are non-interfering. If the runtime is built in debug mode then it will check that the region requirements of all points are actually non-interfering. If you see no further error messages for this index task launch then everything is good.
Assertion failed: (local_version_fields * it->second), function sanity_check, file /Users/alanheirich/Documents/Legion/software/legion_visualization/legion/runtime/legion/legion_analysis.cc, line 6066.
Abort trap: 6

commit 9eb265a5638842b594a2ec0c0918d9a3cd8d493f
Author: Alan Heirich <aheirich@stanford.edu>
Date:   Fri May 19 20:17:33 2017 -0700

    remove c++11isms
    remove statements that cause warnings

**Comment by lightsighter** [comment] 2017-05-20 07:03
Two things:

1. I'm having trouble building this on sapling.  The first error came because the Makefile had -std=c++98.  If I changed it to -std=c++11 I got all the way to the part where I needed OpenGL.h, which I'm not sure that we have on sapling? @streichler did you already install some version of OpenGL either for GPUs or Mesa somewhere?

2. Why is the visualization branch forked off of stable?  There are a lot of bug fixes in master that are not currently in stable?  @aheirich is there anyway you can merge the master branch into the visualization branch such that visualization is upstream of master like all our other development branches?

**Comment by lightsighter** [comment] 2017-05-20 09:58
This issue was caused by aliased region requirements in a point task.  I've added a dynamic check for interfering region requirements in the same point task that will run in debug mode.  It should now report an error for this application.  I'm closing the bug.

**Closed by lightsighter** 2017-05-20 09:58 UTC
