### ISSUE TITLE
regent: compile error with repeated ispace expressions

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#876] opened 2020-06-16 04:21 UTC
Multiple identical `.ispace` expressions in a for loop seems to cause trouble:
```
import "regent"

task dummy(is : ispace(int1d)) end

task main()
  var r = region(ispace(int1d, 4), float)
  var colors = ispace(int1d, 2)
  var p = partition(equal, r, colors)
  for i in colors do
    dummy(p[i].ispace)
    dummy(p[i].ispace)
  end
end
```
yields:
```
$ ./regent.py broken.rg 
...e/sean/legion/legion3/language/src/regent/symbol_table.t:66: Errors reported during typechecking.
broken.rg:11: name '$28' is already defined
    dummy(p[i].ispace)
           ^

stack traceback:
	[C]: in function 'error'
	...home/sean/legion/legion3/language/terra/src/terralib.lua:390: in function 'finishandabortiferrors'
	...al/home/sean/legion/legion3/language/src/common/report.t:56: in function 'error'
	...e/sean/legion/legion3/language/src/regent/symbol_table.t:66: in function 'insert'
	.../home/sean/legion/legion3/language/src/regent/validate.t:57: in function 'intern_variable'
	.../home/sean/legion/legion3/language/src/regent/validate.t:270: in function 'fn'
	/local/home/sean/legion/legion3/language/src/common/ast.t:426: in function 'continuation'
	/local/home/sean/legion/legion3/language/src/common/ast.t:436: in function 'continuation'
	/local/home/sean/legion/legion3/language/src/common/ast.t:431: in function 'continuation'
	.../home/sean/legion/legion3/language/src/regent/validate.t:92: in function 'fn'
	...
	/local/home/sean/legion/legion3/language/src/common/ast.t:436: in function 'continuation'
	/local/home/sean/legion/legion3/language/src/common/ast.t:431: in function 'continuation'
	.../home/sean/legion/legion3/language/src/regent/validate.t:92: in function 'fn'
	/local/home/sean/legion/legion3/language/src/common/ast.t:426: in function 'continuation'
	/local/home/sean/legion/legion3/language/src/common/ast.t:440: in function 'traverse_node_continuation'
	.../home/sean/legion/legion3/language/src/regent/validate.t:302: in function 'validate_variables'
	.../home/sean/legion/legion3/language/src/regent/validate.t:310: in function 'top_task'
	.../home/sean/legion/legion3/language/src/regent/validate.t:315: in function <.../home/sean/legion/legion3/language/src/regent/validate.t:313>
	...al/home/sean/legion/legion3/language/src/regent/passes.t:44: in function <...al/home/sean/legion/legion3/language/src/regent/passes.t:40>
	broken.rg:5: in main chunk
```

**Comment by rupanshusoi** [comment] 2020-06-16 05:46
This is essentially my reproducer of #837 and is an RDIR bug. You can use `-fflow 0` as a workaround for the time being.

**Comment by lightsighter** [comment] 2020-07-13 09:46
@elliottslaughter Can you confirm that this is a duplicate of #837 so we can close it?

**Closed** 2020-07-13 17:21 UTC
Labels: duplicate
