### ISSUE TITLE
Legion: Reduction with non-POD type fails

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#500] opened 2019-03-17 02:29 UTC
When a reduction is defined for a non-POD type, the initialization done here
https://github.com/StanfordLegion/legion/blob/6732fb6f61a631348c2ed7cd1317af444779b3b7/runtime/realm/redop.h#L185
fails. The copy initialization fails because the value at `rhs_ptr` may not be a properly initialized value when the assignment is done. As a workaround (but not a great solution), inserting the statement
`::new(rhs_ptr) typename REDOP::RHS;`
inside the loop, before the assignment, fixes the issue in my code.

**Comment by lightsighter** [comment] 2019-04-11 22:23
Can you give me a little more code around this statement so I can see what some of the types are? Is 'rhs_ptr' a C pointer or some other Legion type?

**Comment by mpokorny** [comment] 2019-04-11 22:44
In my case the REDOP::RHS has type std::vector<_>, so rhs_ptr has type std::vector<_>*. The vector elements have a non-POD generic type, as well, but REDOP::identity is simply an empty vector.

**Comment by lightsighter** [comment] 2019-04-12 06:34
Ok, where did 'rhs_ptr' come from then? Did you get it out of a region in some way or did you declare it yourself?

**Comment by mpokorny** [comment] 2019-04-12 16:02
It's from a region: a field over which the code is doing a reduction (to merge sorted vectors). There are no uninitialized values in the regions when the task is launched.

**Comment by lightsighter** [comment] 2019-04-12 21:03
When you say a reduction, do you mean with Legion 'REDUCE' privileges, or are you using 'READ_WRITE' and doing the reduction yourself? Also, what is writing the field previously?

**Comment by mpokorny** [comment] 2019-04-12 21:53
The region has a single field and one value in the index space; it is initialized using 'WRITE_DISCARD' privileges. The task that has initialized that region then launches an index space task over another region, with 'READ_ONLY' privileges on the second region, and 'REDUCE' privileges on the first (single element) region.Basically, all the values in the 'READ_ONLY' region are being transformed and combined into a single value in the 'REDUCE' region. Does that make sense?

**Comment by lightsighter** [comment] 2019-04-12 22:57
So the problem is inside the task with 'REDUCE' privileges on the region with just a single element? How did you make your reduction operator? Did you remember to provide a SerdezInitFnptr and SerdezFoldFnptr when you registered the reduction operator since it's going to be used with a serdez field?
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion.h#L6857-6876

Also, I would strongly recommend not making regions of just one element. Much better to return the vector by wrapping it in an enclosing type and hooking the three methods for serializing and deserializing non-trivial types that are returned from tasks:
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion.h#L7475-7477

**Comment by mpokorny** [comment] 2019-04-15 19:59
I used the generic version of register_reduction_op function https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion.h#L6854-6855
with a REDOP type that defines apply, fold and identity. I'm not sure that I understand the arguments to the register_reduction_op() function that you quoted. Is there an example of its use in the source tree somewhere?
Looking at the legion.inl file here https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/legion.inl#L8758-8759 has got me wondering about the serdez_redop_* functions and whether I should be calling some such function.

As for your recommendation that I not use a region of one element, are you suggesting that I might be better off doing this reduction "manually" by iterating over the values in the input region?

Thanks for your help, Mike. It is quite likely that I'm missing something important, and I appreciate you having a look at this and helping me sort it out.

**Comment by lightsighter** [comment] 2019-04-16 15:25
Yes, that templated version should also have the optional 'init_fnptr' and 'fold_fnptr' for serdez redop functions. There's not an example of this yet because I think you're the first one to attempt to perform a reduction on a field that is a serdez field. When I was implementing serdez fields I realized they would have this interaction with reductions which is why this interface exists, but it isn't really documented (it's the kind of detail that will be in the Legion manual when @alexaiken finishes writing it). The 'init_fnptr' and 'fold_fnptr' are the functions that the runtime should call to "initialize" and "fold" values for reductions on serdez fields. We can't really synthesize them for you because the serdez part is custom to your application. Here are the types for the functions:

https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/legion_types.h#L1615-1617

Effectively you're implementing the same methods that the runtime would normally synthesize for reduction operators, but just custom to any serdez stuff you want to do. If that's not enough detail let me know and I'll try to has it out some more.

> As for your recommendation that I not use a region of one element, are you suggesting that I might be better off doing this reduction "manually" by iterating over the values in the input region?

Yes, effectively I think you can iterate over the input region (or sub-region) in each task and produce a single value that you return as a future. If you do an index space launch you can also have the runtime apply the reduction operation across the futures as well so that you produce a single future output for an entire index space task launch.

**Comment by mpokorny** [comment] 2019-04-16 21:26
On Tue, 16 Apr 2019 at 09:25, Mike Bauer wrote:
> Yes, that templated version should also have the optional 
> 'init_fnptr' and 'fold_fnptr' for serdez redop functions. 
> There's not an example of this yet because I think you're the 
> first one to attempt to perform a reduction on a field that is a 
> serdez field. When I was implementing serdez fields I realized 
> they would have this interaction with reductions which is why 
> this interface exists, but it isn't really documented (it's the 
> kind of detail that will be in the Legion manual when @alexaiken 
> finishes writing it). The 'init_fnptr' and 'fold_fnptr' are the 
> functions that the runtime should call to "initialize" and 
> "fold" values for reductions on serdez fields. We can't really 
> synthesize them for you because the serdez part is custom to 
> your application. Here are the types for the functions:
>
> https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/legion_types.h#L1615-1617
>
> Effectively you're implementing the same methods that the 
> runtime would normally synthesize for reduction operators, but 
> just custom to any serdez stuff you want to do. If that's not 
> enough detail let me know and I'll try to has it out some more.

OK, I have now changed to using the register_reduction_op() 
function with the additional arguments. Something like the 
following:

Legion::Runtime::register_reduction_op(
  REDOP_ID,
  Realm::ReductionOpUntyped::create_reduction_op<REDOP>(),
  REDOP::init_fn,
  REDOP::fold_fn);

where REDOP is a struct type conforming to a ReductionOp as given 
in redop.h, with the addition of two static functions, init_fn and 
fold_fn. The implementations of init_fn and fold_fn are my best 
guess as to what's expected, based on my review of code in 
legion_tasks.cc. Not sure about the second argument, but it seemed 
the way to create a ReductionOp*. Nevertheless, with these changes 
to my test code the program still crashes as before. The stack 
trace shows that 
Legion::Internal::InstanceBuilder::create_physical_instance() is 
calling Realm::ReductionOp<REDOP>::init(), which is where the 
problem occurs. Changing the implementation of the init() function 
as I noted previously still fixes the crash.

>> As for your recommendation that I not use a region of one 
>> element, are you suggesting that I might be better off doing 
>> this reduction "manually" by iterating over the values in the 
>> input region?
>
> Yes, effectively I think you can iterate over the input region 
> (or sub-region) in each task and produce a single value that you 
> return as a future. If you do an index space launch you can also 
> have the runtime apply the reduction operation across the 
> futures as well so that you produce a single future output for 
> an entire index space task launch.

I had not noticed that function before. I will definitely try it 
out.

Thanks again.

--
Martin

**Comment by mpokorny** [comment] 2019-04-16 22:29
On Tue, 16 Apr 2019 at 15:26, Martin Pokorny wrote:
> On Tue, 16 Apr 2019 at 09:25, Mike Bauer wrote:
>>> As for your recommendation that I not use a region of one 
>>> element, are you
>>> suggesting that I might be better off doing this reduction 
>>> "manually" by
>>> iterating over the values in the input region?
>>
>> Yes, effectively I think you can iterate over the input region 
>> (or sub-region)
>> in each task and produce a single value that you return as a 
>> future. If you do
>> an index space launch you can also have the runtime apply the 
>> reduction
>> operation across the futures as well so that you produce a 
>> single future
>> output for an entire index space task launch.
>
> I had not noticed that function before. I will definitely try it 
> out.

With the change in my code to use execute_index_space() with a 
reduction operation, this issue (if it may be called such) no 
longer affects me at this time. Mike, if you're convinced that the 
original issue is one of user error, I wouldn't mind if you 
decided to close it.

--
Martin

**Comment by lightsighter** [comment] 2019-04-17 22:51
Ok, sounds good. I think if you had implemented the init_fnptr and fold_fnptr methods for your serdez field with reduction it would have worked fine. I'm going to close this issue now.

**Closed by lightsighter** 2019-04-17 22:51 UTC
