### ISSUE TITLE
HTR build failure in CI

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1756] opened 2024-09-10 18:47 UTC
Reported by @mariodirenzo:

> All my CIs based on the CMake build of Legion have been failing with errors like
>
> ```
> /home/gitlab-runner/legion-debug-cmake/runtime/realm/gasnet1/gasnetmsg.cc:1665:
>  undefined reference to `gasneti_thunk_tm'
> ```
>
> The error appeared after https://gitlab.com/StanfordLegion/legion/-/merge_requests/1427 was merged.

Mario, can you provide any additional details on the specific CMake command line, and the system (OS, CUDA, CMake, etc. versions)?

**Comment by elliottslaughter** [comment] 2024-09-23 22:54
@mariodirenzo Please retest this on latest `master`, we've merged various fixes to the CMake build that I think are likely to resolve this.

**Comment by elliottslaughter** [comment] 2024-09-26 17:04
I've been told that CI is passing now, so closing. (If this is not true, feel free to reopen.)

**Comment by mariodirenzo** [comment] 2024-09-26 17:17
Unfortunately, I haven't been able to get a build of Legion using CMake after https://gitlab.com/StanfordLegion/legion/-/merge_requests/1427 was merged.
If the runtime is built properly, I get this error 
```
[0 - 7fd0f5de7c40]    0.000000 {5}{gex}: Failed to load gex wrapper at librealm_gex_wrapper.so
```
when executing the code.
I do not have any time to debug this until mid-October. I'll get in touch when I will have further info

**Comment by seemamirch** [comment] 2024-09-26 17:38
@mariodirenzo - if you can provides details to reproduce I can debug further. I don't see any cmake builds in the CI (the link I have been using for it  - https://lc.llnl.gov/gitlab/stanford-psaap/ci/-/pipelines)

**Comment by seemamirch** [comment] 2024-10-01 23:23
One config that fails with cmake 

1. Build failure with cmake + gasnet1 on lassen (different from what's reported above)
- the same options work on sapling
- the same options but without cmake work on lassen
- the scripts and output from the builds (with/without cmake) are on sapling -> /scratch2/seemah/lassen_cmake_issue/
- build.sh - build script for both, bad.txt is the build output with cmake, good.txt is without cmake
- cmake version 3.23.1

**Comment by muraj** [comment] 2024-10-23 21:48
@seemamirch I don't have access to the internal CI link you posted.  Can you provide the logs of the issue?  If you're seeing the following error, it is likely because you're building with the gasnetex wrapper enabled somehow, which requires either an environment variable set to be able to locate the wrapper library, or it needs to be available in a library search path (e.g. LD_LIBRARY_PATH).  If you do not want to use the gasnetex wrapper, then you need to disable it's use (by default I believe it is _not_ used, so I believe you would be enabling it yourself or through another part of the build system, maybe legate or something?)

If you can provide the full log including the cmake command line used to configure Realm, and the build command and build output, I might be able to reproduce the issue and help resolve it for you.  Thanks!

**Comment by seemamirch** [comment] 2024-10-23 21:58
> @seemamirch I don't have access to the internal CI link you posted. Can you provide the logs of the issue? If you're seeing the following error, it is likely because you're building with the gasnetex wrapper enabled somehow, which requires either an environment variable set to be able to locate the wrapper library, or it needs to be available in a library search path (e.g. LD_LIBRARY_PATH).
> 
> > [0 - 7fd0f5de7c40]    0.000000 {5}{gex}: Failed to load gex wrapper at librealm_gex_wrapper.so
> 
> If you do not want to use the gasnetex wrapper, then you need to disable it's use (by default I believe it is _not_ used, so I believe you would be enabling it yourself or through another part of the build system, maybe legate or something?)
> 
> If you can provide the full log including the cmake command line used to configure Realm, and the build command and build output, I might be able to reproduce the issue and help resolve it for you. Thanks!

I've moved the files to https://sapling2.stanford.edu/~seemah/lassen_cmake_issue/) so you can view them.
my issue is without gasnetex 
The CI link is not relevant for this issue
@mariodirenzo may benefit from your comments above (with gasnetex)

**Comment by muraj** [comment] 2024-10-24 04:50
Okay, looking at "bad.tzt", I see the following line:

> /usr/WS1/mirchandaney1/legion_rc/runtime/realm/realm_config.h:90:2: error: #error Shared memory not supported on GASNET1
 #error Shared memory not supported on GASNET1

This has to do with the shared memory support added several releases ago, and the logic to enable this is here in the cmake build system:
https://github.com/StanfordLegion/legion/blob/4a03402467547b99530042cfe234ceec2cd31b2e/CMakeLists.txt#L822

Which, if gasnet1 is enabled, then this should be _disabled_.  So either your configure command is enabling this feature and overriding the default, or something is wrong with the logic here.

**Comment by mariodirenzo** [comment] 2024-10-29 16:21
As an update, I've been able to get a successful CI of HTR++ binding the latest `master` from scratch and setting `GEX_BUILD_SHARED` and `Legion_USE_GASNETEX_WRAPPER` to `OFF`. From my point of view, we can close the issue

**Comment by seemamirch** [comment] 2024-10-29 21:39
It's possible there was a config issue with my cmake build on lassen - I can't reproduce it. Since @mariodirenzo is also ok with the cmake build of HTR++ - closing this issue

**Closed by seemamirch** 2024-10-29 21:39 UTC
